### ISSUE TITLE
The command >rke etcd save-snapshot --name "snapshotname" doesn't create a snapshot folder under "/opt/rke/etcd-snapshots/backup "

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rke#2316] opened 2020-11-01 19:54 UTC
**RKE version: v1.2.2-rc4**

**Docker version:  19.03.2, build 6a30dfc **

**Operating system and kernel:  Linux-4.15.0-1044-aws-x86_64-with-Ubuntu-18.04-bionic**

**Type/provider of hosts:  ec2 instances**

**cluster.yml file:**

**Steps to Reproduce:**
When users take a snapshot of etcd using rke tool, there is no snapshot dir gets created under backup folder, as a result, the restore command fails to find the snapshot dir and restore fails. 

1. Created a custom cert dir 
>./rke cert generate-csr --cert-dir ./custom-cert 
2. Brought up the rke cluster
> ./rke up —custom-certs —cert-dir --config cluster.yml 
3. Created a snapshot by the name "base-snapshot" 
>./rke etcd snapshot-save —name base_snapshot —config cluster.yml
4. Trying to restore etcd from the snapshot taken 
> ./rke etcd snapshot-restore --name base_snapshot --custom-certs --cert-dir ./custom-cert --config clusterfin.yml 
FATA[0034] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2020-11-01T18:54:47Z" level=fatal msg="stat /backup/base_snapshot: no such file or directory"
 Failed to run backup server container, container logs: time="2020-11-01T18:54:55Z" level=fatal msg="stat /backup/base_snapshot: no such file or directory"
 Failed to run backup server container, container logs: time="2020-11-01T18:55:01Z" level=fatal msg="stat /backup/base_snapshot: no such file or directory"
] 

**Results:*
The problem is when users take snapshot, there is an warning that no name is given as a snapshot, not sure the taking snapshot command has changed, but it went ahead and executed the command but under /opt/rke/etcd-snapshots/backup there is no folder gets created by the snapshot name.
At this point restore form this snapshot fails as restore command is looking for the folder by the snapshot name. 

All the CLI interactions for this issue
**>./rke cert generate-csr --cert-dir ./custom-cert** 
INFO[0000] Running RKE version: v1.2.2-rc4              
.....
......
INFO[0000] [certificates] Generating Kubernetes API server proxy client csr 
INFO[0000] [certificates] Generating etcd-172.31.29.104 csr and key 
INFO[0001] [certificates] Generating etcd-172.31.23.196 csr and key 
INFO[0001] [certificates] Generating etcd-172.31.16.15 csr and key 
INFO[0001] Successfully Deployed certificates at [./custom-cert] 

**./rke up —custom-certs —cert-dir ./custom-cert --config cluster.yml**
WARN[0000] This is not an officially supported version (v1.2.2-rc4) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest 
INFO[0000] Running RKE version: v1.2.2-rc4              
INFO[0000] Initiating Kubernetes cluster      
....
....
INFO[0070] [remove/rke-log-cleaner] Successfully removed container on host [54.219.83.221] 
INFO[0070] [remove/rke-log-cleaner] Successfully removed container on host [54.219.143.21] 
INFO[0071] [remove/rke-log-cleaner] Successfully removed container on host [54.219.73.176] 
INFO[0071] [sync] Syncing nodes Labels and Taints       
INFO[0071] [sync] Successfully synced nodes Labels and Taints 
INFO[0071] [network] Setting up network plugin: canal   
...
INFO[0071] [addons] Setting up coredns                  
...
....
INFO[0071] [addons] CoreDNS deployed successfully       
INFO[0071] [dns] DNS provider coredns deployed successfully 
INFO[0071] [addons] Setting up Metrics Server           
INFO[0071] [addons] Saving ConfigMap for addon rke-metrics-addon to Kubernetes 
INFO[0071] [addons] Successfully saved ConfigMap for addon rke-metrics-addon to Kubernetes 
INFO[0071] [addons] Executing deploy job rke-metrics-addon 
INFO[0071] [addons] Metrics Server deployed successfully 
INFO[0071] [ingress] Setting up nginx ingress controller 
INFO[0071] [addons] Saving ConfigMap for addon rke-ingress-controller to Kubernetes 
INFO[0071] [addons] Successfully saved ConfigMap for addon rke-ingress-controller to Kubernetes 
INFO[0071] [addons] Executing deploy job rke-ingress-controller 
INFO[0071] [ingress] ingress controller nginx deployed successfully 
INFO[0071] [addons] Setting up user addons              
INFO[0071] [addons] no user addons defined              
INFO[0071] Finished building Kubernetes cluster successfully 
 
**./rke etcd snapshot-save —name base_snapshot1 —config cluster.yml**    
sadiapodar@Sadias-MacBook-Pro rke-2.2.x % ./rke etcd snapshot-save  —name base_snapshot1 —config cluster.yml                                               
WARN[0000] This is not an officially supported version (v1.2.2-rc4) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest 
INFO[0000] Running RKE version: v1.2.2-rc4              
**WARN[0000] Name of the snapshot is not specified using [rke_etcd_snapshot_2020-11-01T11:35:45-08:00] == Not sure about this warning** 
INFO[0000] Starting saving snapshot on etcd hosts       
INFO[0000] [dialer] Setup tunnel for host [54.219.73.176] 
INFO[0000] [dialer] Setup tunnel for host [54.219.83.221] 
INFO[0000] [dialer] Setup tunnel for host [54.219.143.21] 
...
...
NFO[0012] Container [etcd-snapshot-once] is still running on host [54.219.73.176]: stderr: [time="2020-11-01T19:45:17Z" level=info msg="Initializing Onetime Backup" name="rke_etcd_snapshot_2020-11-01T11:45:04-08:00"
], stdout: [] 
INFO[0013] Waiting for [etcd-snapshot-once] container to exit on host [54.219.73.176] 
INFO[0013] Removing container [etcd-snapshot-once] on host [54.219.73.176], try #1 

**./rke etcd snapshot-restore --name base_snapshot1 --custom-certs --cert-dir ./custom-cert --config cluster.yml**

WARN[0000] This is not an officially supported version (v1.2.2-rc4) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest 
INFO[0000] Running RKE version: v1.2.2-rc4              
INFO[0000] Checking if state file is included in snapshot file for [base_snapshot1] 
INFO[0000] [dialer] Setup tunnel for host [54.219.73.176] 
INFO[0000] [dialer] Setup tunnel for host [54.219.83.221] 
INFO[0000] [dialer] Setup tunnel for host [54.219.143.21] 
...
...
INFO[0033] Starting container [etcd] on host [54.219.83.221], try #1 
INFO[0033] Starting container [etcd] on host [54.219.143.21], try #1 
INFO[0034] Starting container [etcd] on host [54.219.73.176], try #1 
FATA[0034] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2020-11-01T18:54:47Z" level=fatal msg="stat /backup/base_snapshot: no such file or directory"
 Failed to run backup server container, container logs: time="2020-11-01T18:54:55Z" level=fatal msg="stat /backup/base_snapshot: no such file or directory"
 Failed to run backup server container, container logs: time="2020-11-01T18:55:01Z" level=fatal msg="stat /backup/base_snapshot: no such file or directory"
]

**Comment by sowmyav27** [comment] 2020-11-02 18:19
duplicate of https://github.com/rancher/rke/issues/2315. Closing this.

**Closed by sowmyav27** 2020-11-02 18:19 UTC

**Comment by sadiapoddar** [comment] 2020-11-02 19:07
The issue was the name option didn't "--" and the rke command didn't recognize the name of the snapshot and generated a timestamp-based snapshot. I was able to restore the etcd using the timestamp-based snapshot.

Closing this bug and nothing to fix.
