### ISSUE TITLE
Cluster certificate is not valid for load balancer

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#324] opened 2018-02-06 22:39 UTC
Creating a load balancer for master nodes, kubectl can't connect through the external load balancer because the certificate generated isn't valid for any IPs outside of the master node IPs, 127.0.0.1, and the DNS service IP.

```
Unable to connect to the server: x509: certificate is valid for
  10.18.160.28, 10.18.160.33, 10.18.160.31, 127.0.0.1, 10.233.0.1,
  not 10.18.160.34
```

Is there an option or workaround that allows you to create an external load balancer or VIP with the certificate being generated?

**Comment by superseb** [comment] 2018-02-07 09:56
Not yet, duplicate of https://github.com/rancher/rke/issues/86

**Closed by superseb** 2018-02-07 09:56 UTC
