### ISSUE TITLE
FATA[0336] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

### ISSUE THREAD

**Issue by hack3d** [rancher/rke#1295] opened 2019-04-17 12:53 UTC
**RKE version:**
v0.2.2, v0.1.16

**Docker version: (`docker version`,`docker info` preferred)**
`
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056dbc
 Built:             Thu Apr 11 04:44:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
`

`
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.2
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 565.6GiB
Name: XYZ
ID: 223L:IRSR:PDZH:PBHD:LSWN:G3GS:OVP4:5SN5:JAJI:KK5P:73WP:P6PH
Docker Root Dir: /opt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

`4.9.0-8-amd64`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
`
nodes:
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        worker: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        worker: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        worker: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        worker: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        minio: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        minio: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        minio: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - worker
      labels:
        minio: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
    - address: XXXXXXXXXX
      user: www-data
      docker_socket: /var/run/docker.sock
      role:
        - etcd
        - controlplane
      labels:
        master: true
  
  
ssh_key_path: /opt/ui/data/www-data/.ssh/id_rsa

kubernetes_version: "v1.13.5-rancher1-2"

network:
  plugin: calico

services:
  kube-api:
    extra_args:
      oidc-issuer-url: "https://https://dex.shopservice.1and1.com"
      oidc-client-id: "example-app"
      oidc-username-claim: "name"
      oidc-groups-claim: "groups"
      oidc-ca-file: "/usr/share/ca-certificates/1and1/pukirootca1.crt"
      audit-policy-file: "/opt/conf/k8s-audit/audit_logging.yml"
      audit-log-path: "/opt/logs/audit-log.log"
      audit-log-maxage: 7
      audit-log-maxbackup: 5
      audit-log-maxsize: 100
      audit-log-format: json
      feature-gates: "AdvancedAuditing=true"
      service-cluster-ip-range: 100.80.0.0/13
    extra_binds:
      - "/usr/share/ca-certificates/1and1:/usr/share/ca-certificates/1and1"
      - "/opt/ui/data/www-data/conf/k8s-audit:/opt/conf/k8s-audit"
      - "/opt/ui/data/www-data/logs:/opt/logs"
  kube-controller:
    cluster_cidr: 100.64.0.0/16

  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

addons_include:
  - /opt/ui/data/www-data/rke/dex.yml
`

**Steps to Reproduce:**
1. Fresh Debian Stretch with docker
2. www-data as tooluser and sudo rights for docker
3. rke up

**Results:**
`
rke up
...
INFO[0300] [sync] Syncing nodes Labels and Taints       
INFO[0306] [sync] Successfully synced nodes Labels and Taints 
INFO[0306] [network] Setting up network plugin: calico  
INFO[0306] [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes 
INFO[0306] [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes 
INFO[0306] [addons] Executing deploy job rke-network-plugin 
FATA[0336] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
`

**Comment by Tupeipei** [comment] 2019-04-24 06:05
Did dou fix the problem? I have the same problem...

**Comment by sumanthkumarc** [comment] 2019-05-01 05:11
+me same issue

**Comment by hack3d** [comment] 2019-05-01 06:30
I didn't fix the problem. 
As a workaround we removed the "service-cluster-ip-range: 100.80.0.0/13" option from kube-api. Than the cluster will be builded successful.

**Comment by alena1108** [comment] 2019-06-14 17:07
Closing as a duplicate of https://github.com/rancher/rancher/issues/19189

**Closed by alena1108** 2019-06-14 17:07 UTC
Labels: [zube]: Backlog, kind/bug, team/ca

**Comment by yeongjet** [comment] 2020-05-16 04:54
I solved this by turning off selinux

**Comment by yeongjet** [comment] 2020-05-16 04:54
I solved this by turning off selinux
