### ISSUE TITLE
Failure to verify healthcheck, but manual verification works

### ISSUE THREAD

**Issue by cdata** [rancher/rke#201] opened 2018-01-04 16:55 UTC
**RKE version:**
rke version v0.0.9-dev

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```yaml
nodes:
  - machine_name: control
    address: 192.168.1.9
    role:
      - controlplane
      - etcd
    user: cdata
    docker_socket: /var/run/docker.sock
    ssh_key_path: ./id_rsa
  - machine_name: node-0
    address: 192.168.1.10
    role:
      - worker
    user: cdata
    docker_socket: /var/run/docker.sock
    ssh_key_path: ./id_rsa
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: macaque.house
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    cluster_dns_server: 10.233.0.3
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
network:
  plugin: flannel
authentication:
  strategy: x509
ssh_key_path: ./id_rsa
authorization:
  mode: rbac
ignore_docker_version: false
```

**Steps to Reproduce:**
1. `rke up`
2. Observe printed results

**Results:**
```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.1.9]
INFO[0000] [dialer] Setup tunnel for host [192.168.1.10]
INFO[0000] [state] Found local kube config file, trying to get state from cluster
INFO[0000] [reconcile] Local config is not vaild, rebuilding admin config
INFO[0000] [reconcile] Rebuilding and updating local kube config
INFO[0000] Successfully Deployed local admin kubeconfig at [./.kube_config_cluster.yml]
INFO[0000] [state] Fetching cluster state from Kubernetes
INFO[0030] Timed out waiting for kubernetes cluster to get state
INFO[0030] [certificates] Generating kubernetes certificates
INFO[0030] [certificates] Generating CA kubernetes certificates
INFO[0030] [certificates] Generating Kubernetes API server certificates
INFO[0031] [certificates] Generating Kube Controller certificates
INFO[0031] [certificates] Generating Kube Scheduler certificates
INFO[0031] [certificates] Generating Kube Proxy certificates
INFO[0031] [certificates] Generating Node certificate
INFO[0031] [certificates] Generating admin certificates and kubeconfig
INFO[0032] [reconcile] Reconciling cluster state
INFO[0032] [reconcile] This is newly generated cluster
INFO[0032] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0032] [certificates] Checking image [rancher/rke-cert-deployer:0.1.0] on host [192.168.1.9]
INFO[0032] [certificates] Pulling image [rancher/rke-cert-deployer:0.1.0] on host [192.168.1.9]
INFO[0036] [certificates] Successfully pulled image [rancher/rke-cert-deployer:0.1.0] on host [192.168.1.9]
INFO[0041] [certificates] Checking image [rancher/rke-cert-deployer:0.1.0] on host [192.168.1.10]
INFO[0041] [certificates] No pull necessary, image [rancher/rke-cert-deployer:0.1.0] exists on host [192.168.1.10]
INFO[0047] Successfully Deployed local admin kubeconfig at [./.kube_config_cluster.yml]
INFO[0047] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0047] [etcd] Building up Etcd Plane..
INFO[0047] [etcd] Checking image [quay.io/coreos/etcd:latest] on host [192.168.1.9]
INFO[0047] [etcd] Pulling image [quay.io/coreos/etcd:latest] on host [192.168.1.9]
INFO[0053] [etcd] Successfully pulled image [quay.io/coreos/etcd:latest] on host [192.168.1.9]
INFO[0054] [etcd] Successfully started [etcd] container on host [192.168.1.9]
INFO[0054] [etcd] Successfully started Etcd Plane..
INFO[0054] [controlplane] Building up Controller Plane..
INFO[0054] [sidekick] Checking image [rancher/rke-service-sidekick:0.1.0] on host [192.168.1.9]
INFO[0054] [sidekick] Pulling image [rancher/rke-service-sidekick:0.1.0] on host [192.168.1.9]
INFO[0056] [sidekick] Successfully pulled image [rancher/rke-service-sidekick:0.1.0] on host [192.168.1.9]
INFO[0056] [controlplane] Checking image [rancher/k8s:v1.8.3-rancher2] on host [192.168.1.9]
INFO[0056] [controlplane] Pulling image [rancher/k8s:v1.8.3-rancher2] on host [192.168.1.9]
INFO[0169] [controlplane] Successfully pulled image [rancher/k8s:v1.8.3-rancher2] on host [192.168.1.9]
INFO[0170] [controlplane] Successfully started [kube-api] container on host [192.168.1.9]
INFO[0170] [healthcheck] Start Healthcheck on service [kube-api] on host [192.168.1.9]
FATA[0186] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check /healthz for service [kube-api] on host [192.168.1.9]: Get http://localhost/healthz: Failed to dial to Healthcheck Port [8080] on host [192.168.1.9]: ssh: rejected: connect failed (Connection refused)
```

**Additional notes:**
I manually SSH'd into the control node and curled `http://localhost:8080/healthz`, and received "ok" as a response. The `FATA[0186]` log line makes it kind of confusing, because it suggests it is trying to get `http://localhost/healthz` without a specific port. If it is actually trying to dial this address without the healthcheck port, it makes sense that the connection is refused (nothing is running on that port).

**Comment by cdata** [comment] 2018-01-04 17:15
If I run the command a second time without clearing out the Docker containers, I get a different outcome:

```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.1.9]
INFO[0000] [dialer] Setup tunnel for host [192.168.1.10]
INFO[0000] [state] Found local kube config file, trying to get state from cluster
INFO[0000] [reconcile] Local config is not vaild, rebuilding admin config
INFO[0000] [reconcile] Rebuilding and updating local kube config
INFO[0000] Successfully Deployed local admin kubeconfig at [./.kube_config_cluster.yml]
INFO[0000] [state] Fetching cluster state from Kubernetes
INFO[0030] Timed out waiting for kubernetes cluster to get state
INFO[0030] [certificates] Generating kubernetes certificates
INFO[0030] [certificates] Generating CA kubernetes certificates
INFO[0030] [certificates] Generating Kubernetes API server certificates
INFO[0031] [certificates] Generating Kube Controller certificates
INFO[0031] [certificates] Generating Kube Scheduler certificates
INFO[0031] [certificates] Generating Kube Proxy certificates
INFO[0031] [certificates] Generating Node certificate
INFO[0032] [certificates] Generating admin certificates and kubeconfig
INFO[0032] [reconcile] Reconciling cluster state
INFO[0032] [reconcile] This is newly generated cluster
INFO[0032] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0032] [certificates] Checking image [rancher/rke-cert-deployer:0.1.0] on host [192.168.1.9]
INFO[0032] [certificates] No pull necessary, image [rancher/rke-cert-deployer:0.1.0] exists on host [192.168.1.9]
INFO[0038] [certificates] Checking image [rancher/rke-cert-deployer:0.1.0] on host [192.168.1.10]
INFO[0038] [certificates] No pull necessary, image [rancher/rke-cert-deployer:0.1.0] exists on host [192.168.1.10]
INFO[0043] Successfully Deployed local admin kubeconfig at [./.kube_config_cluster.yml]
INFO[0043] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0043] [etcd] Building up Etcd Plane..
INFO[0043] [etcd] Container [etcd] is already running on host [192.168.1.9]
INFO[0043] [etcd] Successfully started Etcd Plane..
INFO[0043] [controlplane] Building up Controller Plane..
INFO[0043] [sidekick] Sidekick container already created on host [192.168.1.9]
INFO[0043] [controlplane] Container [kube-api] is already running on host [192.168.1.9]
INFO[0043] [healthcheck] Start Healthcheck on service [kube-api] on host [192.168.1.9]
INFO[0043] [healthcheck] service [kube-api] on host [192.168.1.9] is healthy
INFO[0043] [controlplane] Checking image [rancher/k8s:v1.8.3-rancher2] on host [192.168.1.9]
INFO[0043] [controlplane] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [192.168.1.9]
INFO[0043] [controlplane] Successfully started [kube-controller] container on host [192.168.1.9]
INFO[0043] [healthcheck] Start Healthcheck on service [kube-controller] on host [192.168.1.9]
INFO[0044] [healthcheck] service [kube-controller] on host [192.168.1.9] is healthy
INFO[0044] [controlplane] Checking image [rancher/k8s:v1.8.3-rancher2] on host [192.168.1.9]
INFO[0044] [controlplane] No pull necessary, image [rancher/k8s:v1.8.3-rancher2] exists on host [192.168.1.9]
INFO[0044] [controlplane] Successfully started [scheduler] container on host [192.168.1.9]
INFO[0044] [healthcheck] Start Healthcheck on service [scheduler] on host [192.168.1.9]
INFO[0045] [healthcheck] service [scheduler] on host [192.168.1.9] is healthy
INFO[0045] [controlplane] Successfully started Controller Plane..
INFO[0045] [authz] Creating rke-job-deployer ServiceAccount
FATA[0070] [auths] Failed to apply RBAC resources: Failed to apply the ServiceAccount needed for job execution: Post https://192.168.1.9:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")
```

It looks like maybe there could be a timing problem checking `http://localhost:8080/healthz`, and the second time we run `rke up`, it regenerates the certificates which causes auth to fail? Just speculating. Your advice would be appreciated.

**Comment by galal-hussein** [comment] 2018-01-04 17:20
@cdata regarding the first issue, the logs message `http://localhost/healthz` is because we add a custom healthcheck dialer with the right port, but it doesn't mean that the healthcheck tries to probe port 80, it could be a timing issue, and the kube-api is just not ready in time, can you please try to do `rke remove` and try again to see if the problem reproduce.

regarding the second issue, because the first run failed before it could have the chance to save the certificates, so rke regenerated the certificates hence this error.

**Comment by cdata** [comment] 2018-01-04 17:23
Thanks for the response!

I was able to "fix" the health check problem by adding a sleep (five seconds) just before the dial for `http://localhost:8080/healthz`, so it definitely seems like a timing issue.

I will see how `rke remove` affects the situation.

**Comment by cdata** [comment] 2018-01-04 17:38
After using `rke remove` to clean before retry, and keeping the sleep in before the health check, I can successfully provision the cluster. Thank you for the advice!

**Comment by galal-hussein** [comment] 2018-01-04 17:45
@cdata No problem, i opened #202 to consider increasing timeouts for healthcheck and addons deployments, closing this issue for now, thanks! please reopen if you have any other concerns.

**Closed by galal-hussein** 2018-01-04 17:45 UTC

**Comment by yuanjinyong** [comment] 2018-01-22 06:42
I used rke_linux-amd64-v0.0.12-dev, and also have this issue. Error message is following:
**[root@bogon k8s]# rke --debug up --config /opt/k8s/test.yml**
```
INFO[0047] Successfully Deployed local admin kubeconfig at [/opt/k8s/.kube_config_test.yml] 
INFO[0047] [certificates] Successfully deployed kubernetes certificates to Cluster nodes 
INFO[0047] [etcd] Building up Etcd Plane..              
INFO[0047] [etcd] Container [etcd] is already running on host [192.168.42.140] 
DEBU[0047] [etcd] Checking if container [etcd] is eligible for upgrade on host [192.168.42.140] 
DEBU[0047] [etcd] Container [etcd] is not eligible for updgrade on host [192.168.42.140] 
INFO[0047] [etcd] Successfully started Etcd Plane..     
INFO[0047] [controlplane] Building up Controller Plane.. 
DEBU[0047] Checking if container [service-sidekick] is running on host [192.168.42.135] 
INFO[0047] [sidekick] Sidekick container already created on host [192.168.42.135] 
INFO[0047] [controlplane] Container [kube-api] is already running on host [192.168.42.135] 
DEBU[0047] [controlplane] Checking if container [kube-api] is eligible for upgrade on host [192.168.42.135] 
DEBU[0047] [controlplane] Container [kube-api] is not eligible for updgrade on host [192.168.42.135] 
INFO[0047] [healthcheck] Start Healthcheck on service [kube-api] on host [192.168.42.135] 
DEBU[0047] [ssh] Checking private key                   
DEBU[0047] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0053] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0058] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0063] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0068] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0074] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0079] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0084] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0090] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
DEBU[0095] [healthcheck] Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
FATA[0100] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check /healthz for service [kube-api] on host [192.168.42.135]: Get https://localhost/healthz: Failed to dial to Local Port [6443] on host [192.168.42.135]: ssh: rejected: connect failed (open failed) 
```

From the log message, timeouts has already increased.
And I tried following, the connect  is ok, the 6443 port can be connected:
**[root@bogon k8s]# curl https://192.168.42.135:6443/healthz --insecure**
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/healthz\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```


**Following are my environment:**
------------------------------------------------------------------------------------------------
1. OS
**[root@bogon k8s]# uname -a**
`Linux bogon 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
**[root@bogon k8s]# rpm -q centos-release**
`centos-release-7-4.1708.el7.centos.x86_64`

------------------------------------------------------------------------------------------------
2. RKE
**[root@bogon k8s]# rke**
```
NAME:
   rke - Rancher Kubernetes Engine, Running kubernetes cluster in the cloud

USAGE:
   rke [global options] command [command options] [arguments...]
   
VERSION:
   v0.0.12-dev
   
AUTHOR(S):
   Rancher Labs, Inc. 
   
COMMANDS:
     up       Bring the cluster up
     remove   Teardown the cluster and clean cluster nodes
     version  Show cluster Kubernetes version
     config   Setup cluster configuration
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d    Debug logging
   --help, -h     show help
   --version, -v  print the version
```

------------------------------------------------------------------------------------------------
3. Docker
**[root@bogon ~]# docker version**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**[root@bogon ~]# docker info**
```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.781 GiB
Name: bogon
ID: Q6RA:HUCE:T6FN:5U5X:ONRF:DMHD:3ZTY:UFIH:NG4U:CX5T:FEVY:W7TX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

------------------------------------------------------------------------------------------------
4. config file
**/opt/k8s/test.yml**
```
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 192.168.42.140
  role:
  - etcd
  user: root
- address: 192.168.42.135
  role:
  - controlplane
  user: root
- address: 192.168.42.136
  role:
  - worker
  user: root
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    extra_args: {}
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: 
      fail-swap-on: false
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    cluster_dns_server: 10.233.0.3
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
network:
  plugin: flannel
  options: {}
authentication:
  strategy: x509
  options: {}
addons: ""
system_images:
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
ssh_key_path: ~/.ssh/id_rsa
authorization:
  mode: rbac
  options: {}
enforce_docker_version: false
```

**Comment by superseb** [comment] 2018-01-22 10:52
Is there anything in the `kube-api` log that explains a possible delay?

**Comment by yuanjinyong** [comment] 2018-01-23 02:16
I find the error message in /var/log/messages file:
```
Jan 23 10:08:01 localhost sshd[16841]: Accepted publickey for root from 192.168.42.139 port 35512 ssh2: RSA SHA256:Ez0tFiv0YpDb8sIr5Ozkku4BcfO+fIQtdEgEE46ehoI
Jan 23 10:08:01 localhost systemd-logind: New session 120 of user root.
Jan 23 10:08:01 localhost systemd: Started Session 120 of user root.
Jan 23 10:08:01 localhost systemd: Starting Session 120 of user root.
**Jan 23 10:08:01 localhost sshd[16841]: error: connect to localhost port 6443 failed: Permission denied**
```

**Comment by yuanjinyong** [comment] 2018-01-23 02:18
Another question, the log-dir arg for k8s doesn't take effect.
I add the log dir args in test.yml:
...
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    extra_args: {}
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args:
      **logtostderr: false
      log-dir: /var/log/kube-apiserver.log**
...

Confirm the args in master node:
**[root@bogon /]# ps -ef|grep etcd**
```
root      16734  16717  3 10:07 ?        00:00:00 /usr/local/bin/etcd --name=etcd-192.168.42.141 --data-dir=/etcd-data --advertise-client-urls=http://192.168.42.141:2379,http://192.168.42.141:4001 --listen-client-urls=http://0.0.0.0:2379 --initial-advertise-peer-urls=http://192.168.42.141:2380 --listen-peer-urls=http://0.0.0.0:2380 --initial-cluster-token=etcd-cluster-1 --initial-cluster=etcd-192.168.42.141=http://192.168.42.141:2380 --initial-cluster-state=new
root      16780  16763 74 10:07 ?        00:00:04 kube-apiserver --insecure-bind-address=127.0.0.1 --bind-address=0.0.0.0 --insecure-port=0 --secure-port=6443 --cloud-provider= --allow_privileged=true --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --service-cluster-ip-range=10.233.0.0/18 --admission-control=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --runtime-config=batch/v2alpha1 --runtime-config=authentication.k8s.io/v1beta1=true --storage-backend=etcd3 --etcd-servers=http://192.168.42.141:2379 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --tls-cert-file=/etc/kubernetes/ssl/kube-api.pem --tls-private-key-file=/etc/kubernetes/ssl/kube-api-key.pem --service-account-key-file=/etc/kubernetes/ssl/kube-api-key.pem --logtostderr=false --log-dir=/var/log/kube-apiserver.log
```
**--logtostderr=false --log-dir=/var/log/kube-apiserver.log**


But I can't find the log file in /var/log/ directory.
