### ISSUE TITLE
kube-apiserver [FATAL tini (6)] exec /opt/rke/entrypoint.sh failed: No such file or directory

### ISSUE THREAD

**Issue by pdhung** [rancher/rke#858] opened 2018-08-13 14:43 UTC
**RKE version:**
0.1.9
**Docker version: (`docker version`,`docker info` preferred)**
17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal

**cluster.yml file:**
[cluster.yml.txt](https://github.com/rancher/rke/files/2286113/cluster.yml.txt)
# standard cluster.yml, only specify node plane, info, address.
system_images:
  kubernetes: rancher/hyperkube:v1.11.1-rancher1
  alpine: rancher/rke-tools:v0.1.13
  nginx_proxy: rancher/rke-tools:v0.1.13
  cert_downloader: rancher/rke-tools:v0.1.13
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.13

**Results:**
kube-apiserver cannot start, therefore healthcheck is not successful, and RKE stop.

RKE outputs: [log.txt](https://github.com/rancher/rke/files/2286109/log.txt)
FATA[0087] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [IP.xx.xx.xx]: Get https://localhost:6443/healthz: Unable to access the service on localhost:6443. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: [FATAL tini (6)] exec /opt/rke/entrypoint.sh failed: No such file or directory

control plane nodes:
kube-apiserver on hyperkube 1.11.1 failed to start
error: [FATAL tini (6)] exec /opt/rke/entrypoint.sh failed: No such file or directory

** Note **:
0.1.9-rc6 run OK with rke-tools 0.1.12, error with rke-tools 0.1.13
0.1.9: error with 0.1.13. On 0.1.12 it has another error.

**Comment by superseb** [comment] 2018-08-13 15:00
Please provide all steps to reproduce, including full `cluster.yml` and debug output.

**Comment by pdhung** [comment] 2018-08-14 08:32
@superseb I updated the information.

**Comment by moelsayed** [comment] 2018-08-17 15:28
@pdhung Your logs indicate that you are using v0.1.9-rc6. Can you please try using v0.1.9 ?

**Comment by galal-hussein** [comment] 2018-09-05 21:14
@pdhung i can't reproduce on Centos 7 with the same cluster.yml file with the latest rke rc, closing the bug but please feel free to reopen if you still have the problem.

**Closed by galal-hussein** 2018-09-05 21:14 UTC
Labels: bug, more-info
