### ISSUE TITLE
administratively prohibited (open failed) 

### ISSUE THREAD

**Issue by kentinchen** [rancher/rke#117] opened 2017-12-07 05:05 UTC
Docker version 17.06.2-ol, build d02b7ab

FATA[0000] Failed to set up SSH tunneling for Etcd host [prd-svr01]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to Docker socket: ssh: rejected: administratively prohibited (open failed)

**Comment by superseb** [comment] 2017-12-07 09:25
Duplicate of https://github.com/rancher/rke/issues/93

**Closed by superseb** 2017-12-07 09:25 UTC
