### ISSUE TITLE
Support the SSH agent

### ISSUE THREAD

**Issue by zommarin** [rancher/rke#218] opened 2018-01-11 09:30 UTC
**RKE version:**
v0.0.9-dev

When running RKE it would be nice if it could use the SSH key credentials from the SSH agent just as SSH itself does. This way we do not have to specify the private key password when running RKE (which SSH agent users in general prefers not to do).

**Comment by superseb** [comment] 2018-01-11 09:32
Can you check if this is a duplicate of https://github.com/rancher/rke/issues/192?

**Comment by zommarin** [comment] 2018-01-11 09:36
#192 is related, but not the same in my opinion. This issue is however one possible solution for issue #192. Another possible solution for #192 would be to cache the password and not ask for it several times.

**Comment by zommarin** [comment] 2018-01-11 09:39
I would prefer that RKE never (not even once) asks for the password, instead it gets the credentials from the SSH Agent, if available. That way I would feel more secure as less secrets are exposed to RKE.

**Comment by ibuildthecloud** [comment] 2018-01-11 20:54
I'd love to see support for this too.  We use golang.org/x/crypto/ssh for SSH.  So the question is whether that library support SSH agent.

**Comment by ibuildthecloud** [comment] 2018-01-11 20:55
Sure seems like there is some support, but not really sure how to use it.

https://godoc.org/golang.org/x/crypto/ssh/agent

**Comment by rickard-von-essen** [comment] 2018-02-16 13:04
[Here is an example](https://github.com/hashicorp/packer/blob/master/builder/amazon/common/ssh.go#L95-L111) of how we use the SSH agent in Packer.

**Comment by rickard-von-essen** [comment] 2018-02-23 16:30
I've done a ugly fix for this that works for my personal use, but I'd like to do a proper PR but I'l like some comments before completing it.

I would like to remove password prompting and instead fail with a proper error message if the private key is encrypted.
And add a new configuration option `ssh_agent` (bool) which defaults to false, if true enable using the SSH agent.

**Comment by moelsayed** [comment] 2018-03-06 19:30
Tested and confirmed working with latest master.

**Closed by moelsayed** 2018-03-06 19:30 UTC
Labels: resolved, to-test

**Comment by rickard-von-essen** [comment] 2018-03-06 20:32
Fixed in #387

**Comment by zommarin** [comment] 2018-03-09 12:05
Thanks Guys! Great job!

**Comment by rossedman** [comment] 2018-03-11 20:22
@moelsayed @superseb does this mean that if we have a custom ssh_config with bastion proxies it will work?
