### ISSUE TITLE
Allow some method for custom PKI

### ISSUE THREAD

**Issue by techninja1008** [rancher/rke#499] opened 2018-04-12 18:18 UTC
In some instances, it is very useful to have control over the certificates and keys used to set up a cluster. To allow for this options could be added to the cluster.yml file to either specify the certificates and keys to be used for particular things, or, more powerfully, specify a path to some sort of arbitrary executable which, when passed a specific set of parameters, outputs either an appropriate key or certificate to standard out for RKE to use in provisioning a cluster. In this instance, it would be assumed that that executable is available on the host, and handles its own idempotence and storage of certificates and keys.

**Comment by galal-hussein** [comment] 2018-04-27 19:34
Duplicate of https://github.com/rancher/rke/issues/450

**Closed by galal-hussein** 2018-04-27 19:34 UTC
Labels: enhancement
