### ISSUE TITLE
Error with metrics-server

### ISSUE THREAD

**Issue by hameno** [rancher/rke#866] opened 2018-08-19 14:05 UTC
**RKE version:** 0.1.9

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** bare-metal

**cluster.yml file:** 

**Steps to Reproduce:**
* Updated cluster using rke 0.1.9 with

`kubernetes_version: "v1.10.5-rancher1-2"`

and it installed the new metrics-server (heapster was already removed)

**Results:**
I'm getting an error when trying to query kubectl top node/pod:
`Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)`

The logs of the metrics-server print the following lines:
`E0819 14:01:22.951266       1 authentication.go:64] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-requestheader-ca"), x509: certificate signed by unknown authority]`

**Comment by galal-hussein** [comment] 2018-08-27 22:16
@hameno i am not able to reproduce when upgrading from v0.1.8 to v0.1.9, here are my steps:

- rke up (version v0.1.8) with the cluster.yml
```
---
nodes:
  - address: x.x.x.x
    user: ubuntu
    role: [etcd,controlplane,worker]
  - address: y.y.y.y
    user: ubuntu
    role: [etcd,controlplane,worker]
  - address: z.z.z.z
    user: ubuntu
    role: [etcd,controlplane,worker]

kubernetes_version: "v1.10.5-rancher1-2"
```
- use rke up with v0.1.9

i can see metrics server being created:
```
kubectl get pods --all-namespaces -o wide
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE       IP               NODE
kube-system     metrics-server-57bccd98fd-r24dt           1/1       Running     0          1h        10.42.2.2        18.130.227.62
```

and can query kubectl top node/pods normally:
```
kubectl top nodes
NAME             CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%   
18.130.225.126   86m          4%        1629Mi          42%       
18.130.227.62    106m         5%        1841Mi          47%       
35.176.147.198   113m         5%        1675Mi          43%

kubectl top pods --all-namespaces
NAMESPACE       NAME                                    CPU(cores)   MEMORY(bytes)   
ingress-nginx   default-http-backend-564b9b6c5b-597ck   0m           3Mi             
ingress-nginx   nginx-ingress-controller-826z5          2m           62Mi            
ingress-nginx   nginx-ingress-controller-jvp95          2m           63Mi            
ingress-nginx   nginx-ingress-controller-xbzmn          2m           62Mi            
kube-system     canal-s6xs6                             13m          44Mi            
kube-system     canal-t222g                             12m          39Mi            
kube-system     canal-vwc9h                             14m          44Mi            
kube-system     kube-dns-5ccb66df65-8pbb9               0m           22Mi            
kube-system     kube-dns-autoscaler-6c4b786f5-g4n8q     0m           6Mi             
kube-system     metrics-server-57bccd98fd-r24dt         0m           12Mi
```

can you describe in details what are your steps, to try and reproduce the problem

**Comment by hameno** [comment] 2018-08-28 04:14
i don't know how to reproduce, it happened with our production cluster but not with our development cluster. do you have any idea on how we could fix this?

**Comment by galal-hussein** [comment] 2018-08-28 17:25
@hameno the error indicate that the metrics server is not able to authenticate because ca injected within pod doesn't match the right one used in the cluster, can you try to delete the pod and see if it will revert to a right state, also it might help to describe the deployment object of the metrics server as long as the following commands:
```
docker inspect kube-apiserver
docker logs kube-apiserver
```

**Comment by galal-hussein** [comment] 2018-09-04 19:43
@hameno closing the issue as i can't reproduce it and the metrics server seems to authenticate correctly with the kubeapi, please reopen if you still having the problem.

**Closed by galal-hussein** 2018-09-04 19:43 UTC
Labels: bug

**Comment by galal-hussein** [comment] 2018-09-10 18:48
The error was due to a bug in rke where it doesn't fetch the requestheader and proxy certificates, so it reacreated those certificates each time the user adds a node, to reproduce the problem:

1- start rke up with 1 node with all roles
2- add second and third node with all roles as well

you should see the following logs in metrics server:
```
E0910 18:12:53.370389       1 authentication.go:64] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-requestheader-ca"), x509: certificate signed by unknown authority]
```

I added a fix to include these certs in the fetch certificates and should work fine with fresh installs, however to upgrade from a broken setup, follow the following steps:

1- delete the requestheader and proxy certs on each node:
```
sudo rm -f /etc/kubernetes/ssl/kube-apiserver-proxy-client* /etc/kubernetes/ssl/kube-apiserver-requestheader*
```
2- update rke to the latest which contain the fix
3- run rke up
4- restart kube-apiserver and controller manager on each node
```
sudo docker restart kube-apiserver kube-controller-manager
```
5- restart the metrics server pod
```
kubectl delete pod -l k8s-app=metrics-server -n kube-system
```

**Comment by mitchellmaler** [comment] 2018-09-12 02:03
@galal-hussein What will be the process if my servers were created by rancher? Will I have to wait for the next rancher version?

**Comment by galal-hussein** [comment] 2018-09-12 03:38
@mitchellmaler yes the next version should have an updated version of rke, however there is a manual workaround also, basically you can replicate the same steps mentioned in the comment https://github.com/rancher/rke/issues/866#issuecomment-420019920 however instead of step 1, 2, and 3 you can:

1,2- check the saved certificates for kubeapi requestheader and kubeapi proxy client in kubernetes secrets, you should find them using the following command:
```
kubectl get secret/kube-apiserver-requestheader -n kube-system -o yaml
kubectl get secret/kube-apiserver-proxy-client -n kube-system -o yaml
```
3- decode the cert/key pair for each secret and replace them on all nodes

you should after that continue with the steps and metrics server should work normally.

**Comment by gregkeys** [comment] 2018-10-25 03:38
Im experiencing this on all my clusters created by rancher, I see a couple methods to fix, but I don't want to experiment, is there an official way to fix this?

**Comment by gregkeys** [comment] 2018-11-18 20:16
@galal-hussein I'm at a point of having to rebuild 20 nodes to fix this error and would like to avoid that if possible. Can you clarify the steps to correct this problem. 

How do I decode and replace cert/key pair on each node, can I do this with kubectl, or do I need to ssh into each node.

**Comment by sonnysideup** [comment] 2019-03-04 17:36
Either this issue still exists today, or I'm doing something terribly wrong.

**os**: Ubuntu 16.04.5 LTS
**rke**: v0.1.16
**docker**: 17.03.3-ce
**kubernetes**: v1.11.6
**provider**: VirtualBox via Vagrant

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
  config.vm.provision :file, source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.define "node-0" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.network :private_network, ip: "192.168.50.10"
    c.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
  end
  config.vm.define "node-1" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.network :private_network, ip: "192.168.50.11"
    c.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
  end
end
```

### RKE cluster.yml

```yaml
ssh_key_path: <homdir>/.ssh/id_rsa
ignore_docker_version: false

nodes:
  - address: 192.168.50.10
    user: vagrant
    port: 22
    role: [controlplane,worker,etcd]
  - address: 192.168.50.11
    user: vagrant
    port: 22
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

### Result:

The 2-node cluster comes up provision and, shortly thereafter, the API intermittently stops responding. Inside the VMs, I noticed that `kube-apiserver` continually causes CPU spikes.

![image](https://user-images.githubusercontent.com/65274/53751020-4f112780-3e79-11e9-8a7d-d3f53aa01e9e.png)

After checking the logs for both instances I noticed that the **metrics-server** is most likely causing this issue:

For reference: this show logs of both **kube-apiserver** containers where the top pane is the VM trying to contact to **metric-server** running on the other node (bottom pane)
![image](https://user-images.githubusercontent.com/65274/53751158-a616fc80-3e79-11e9-8beb-6d1527504ecb.png)

I'm basically trying to the follow the [Rancher HA installation instructions](https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/#create-the-rancher-cluster-yml-file) using RKE, but this just does not work.

**Comment by mboudet** [comment] 2019-03-22 09:47
Hi,

We have the same issue following the [quickstart manual install](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/#2-install-rancher)

We use 4 nodes, 3 of them as as an etcd/control plane/worker, and the last one as a worker.
The kube-apiserver containers seem to have random cpu spikes on all three nodes where they are launched.

The logs in kube-apiserver are mostly the same as @sonnysideup .

On the node where the metricserver is up, we have this : 

![image](https://user-images.githubusercontent.com/17642511/54814108-587afc00-4c8f-11e9-8bf7-d82180149197.png)

On the other two nodes, something like this :

![image](https://user-images.githubusercontent.com/17642511/54814156-721c4380-4c8f-11e9-8c91-88e7f660cdd2.png)

The metrics container does not show any logs since we added the nodes.

We do not have any application launched.

**Comment by superseb** [comment] 2019-03-22 09:50
This issue is regarding certificate issues, not load related issues. The issue you are seeing is tracked in https://github.com/rancher/rancher/issues/17248
