### ISSUE TITLE
RKE generated kubeconfig points to a node, should allow a loadbalancer to be specified.

### ISSUE THREAD

**Issue by skyscooby** [rancher/rke#1673] opened 2019-09-30 00:47 UTC
**RKE version:**
0.2.8

**Steps to Reproduce:**
Bring up any cluster with rke up.

The generated kubeconfig file seems to reference the last node directly.. this makes the generated kubeconfig dependant on the last node provisioned and forces a user to edit the file to switch over to a load balanced configuration after every RKE interaction.
`server: "https://192.168.50.5:6443"`

**Expectation:**
Similar to how the certificate configuration section allows additional san entries if one is using a load balancer the RKE configuration should allow the user to specify their virtual IP address in the configuration so the resulting kubeconfig is generated using the redundant endpoint rather than just pointed at one node. (you could even consider automatically adding this endpoint to the san list when present as it would be necessary to avoid x509 errors)

**Comment by superseb** [comment] 2019-10-02 20:56
Duplicate of https://github.com/rancher/rke/issues/705

**Closed by superseb** 2019-10-02 20:56 UTC
