### ISSUE TITLE
feature request : nodelocaldns provider support

### ISSUE THREAD

**Issue by aderumier** [rancher/rke#1331] opened 2019-05-07 16:13 UTC
Hi,

it could be great to add support for nodelocaldns provider

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns

(it's for deploying a local dns cache on each node)

**Comment by superseb** [comment] 2019-05-08 09:08
Duplicate of https://github.com/rancher/rke/issues/1050

**Closed by superseb** 2019-05-08 09:08 UTC
