### ISSUE TITLE
Support customized docker graph

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [rancher/rke#226] opened 2018-01-14 13:26 UTC
By default, docker lib places at `/var/lib/docker`, we can set `graph` in `/etc/docker/daemon.json` to choose another dir, such as `/data/docker` in the most of cloud nodes.

However, RKE's kubelet service hardcode it to `/var/lib/docker`, see

https://github.com/rancher/rke/blob/master/services/kubelet.go#L70

Can we add a attribute `dockerGraph` to Host config:

https://github.com/tanmer/types/commit/2ac8c65f4871957ec4ed7c22df08372deeec46c2

**Comment by galal-hussein** [comment] 2018-01-14 13:28
@xiaohui-zhangxh I think this is duplicate of #197, adding support for extra binds will solve such a problem

**Comment by xiaohui-zhangxh** [comment] 2018-01-14 13:35
@galal-hussein I think this should be an option for changing default Docker graph path(`/var/lib/docker`), instead of extra binds. Sure, about the coding side, this is an duplicate issue on changing file kubelet.go

**Comment by bmdepesa** [comment] 2018-05-10 21:26
Provisioned a VM and changed graph location through /etc/docker/daemon.json, then restarted Docker and verified location was changed.
Added VM as node to custom cluster. 
Node was provisioned correctly.
Workloads/SD are deploying correctly.

**Closed by bmdepesa** 2018-05-10 21:26 UTC
Labels: enhancement, resolved, to-test
