### ISSUE TITLE
Generated SSL certificate verify failure

### ISSUE THREAD

**Issue by zedtux** [rancher/rke#604] opened 2018-05-11 10:23 UTC
I use rke from my Mac to install k8s on my VPS, all went fine, and BTW it's a very nice tool 👍.

I'm using it to build my own Kubernetes cluster for Gitlab (run tests and isolated environments).
I was able to import the k8s cluster in Gitlab and now I need to continue the Gitlab setup by installing Helm tiller (Gitlab has an "Install" button to do so).

Unfortunately the installation fails with the following message:

```
Kubernetes error: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

Then I opened Safari and went to the server URL and got

<img width="700" alt="this_connection_is_not_private" src="https://user-images.githubusercontent.com/478564/39920046-f6c283aa-5515-11e8-8cf2-346abac4b8a2.png">

And the certificate is the following

<img width="487" alt="screen shot 2018-05-11 at 12 22 01" src="https://user-images.githubusercontent.com/478564/39920050-fcfd3206-5515-11e8-8ed7-e0b420771a13.png">

Is there a way to install a valid SSL certificate or to go with Letsencrypt?

**Comment by galal-hussein** [comment] 2018-05-16 14:37
@zedtux this is duplicate of https://github.com/rancher/rke/issues/450, please follow the progress of the problem there

**Closed by galal-hussein** 2018-05-16 14:37 UTC
Labels: question

**Comment by zedtux** [comment] 2018-05-17 05:42
Thank you @galal-hussein

**Comment by Zwordi** [comment] 2019-06-06 12:59
Hi @zedtux,

Did you get it working ?
Thanks

**Comment by zedtux** [comment] 2019-06-06 13:22
Sorry @Zwordi I'm no more using `rke`. I don't remember if I fixed it or not, sorry.
