### ISSUE TITLE
Upgrade to 1.24.x results in older (pre-upgrade) pods unable to terminate due to "Error deleting network when building cni runtime conf: could not retrieve port mappings: key is not found"

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#2998] opened 2022-08-03 16:14 UTC
**RKE version:** 1.3.x

**Docker version: (`docker version`,`docker info` preferred)** Not applicable

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Not applicable

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Not applicable

**cluster.yml file:** Not applicable

**Steps to Reproduce:**
Have a cluster that is created on 1.23 or older. Upgrade to 1.24.x

**Results:**

See that OLDER (pre-upgrade) pods get stuck in terminating and the kubelet emits logs like
```
Error deleting network when building cni runtime conf: could not retrieve port mappings: key is not found
 ```

This is related to https://github.com/rancher/rke/issues/2993 but should be resolved by https://github.com/Mirantis/cri-dockerd/issues/52

**Comment by sowmyav27** [comment] 2022-08-03 16:26
Same as - https://github.com/rancher/rancher/issues/38270

**Comment by snasovich** [comment] 2022-08-03 16:31
Closing as duplicate of https://github.com/rancher/rancher/issues/38270.

**Closed as completed by snasovich** 2022-08-03 16:31 UTC
