### ISSUE TITLE
`rke up` doesn't fail when kubernetes_version isn't support

### ISSUE THREAD

**Issue by tchernomax** [rancher/rke#1686] opened 2019-10-09 16:58 UTC
**RKE version:**
v0.3.0

**cluster.yml file:**

```yaml
nodes:
  - …
network:
  plugin: calico
kubernetes_version: "v1.14.6-rancher1-1"
```
(nothing else, no `system_images`)

**Steps to Reproduce:**

`rke up`

**What was expected:**

> Each version of RKE has a specific list of supported Kubernetes versions. If a version is defined in kubernetes_version in the cluster.yml and is not found in this list, then RKE will error out.

```
% yq .kubernetes_version cluster.yml
"v1.14.6-rancher1-1"
% rke config -l -a
v1.14.7-rancher1-1
v1.16.1-rancher1-1
v1.13.11-rancher1-1
v1.15.4-rancher1-2
```

`v1.14.6-rancher1-1` isn't in the supported version list, so `rke up` should *error out*.

**What I saw:**

no error, deployment goes on.

Also rancher/rke-tools was updated from v0.1.42 to v0.1.50 ; even if it should have stay in v0.1.42 as expected of `kubernetes_version: v1.14.6-rancher1-1`.
cf. https://github.com/rancher/kontainer-driver-metadata/blob/master/rke/k8s_rke_system_images.go#L1183

**Note**

If I misunderstand the documentation could you precise the sentence:

> If a version is defined in kubernetes_version in the cluster.yml and is not found in this list, then RKE will error out.

Thanks in advance

**Comment by alena1108** [comment] 2019-10-17 05:27
@tchernomax thanks for reporting the issue! Supported versions - returned by rke config -l -a - can be read as recommendation, not a requirement. Those are the versions that we officially cover by SLA for Rancher customers. Unless there is a technical issue with launching deprecated kubernetes version - RKE will continue supporting legacy versions. If there is a technical reason preventing rke from deploying a certain k8s version, rke will error out.

I'll open the bug in docs so this is more clear to the users. Closing this particular issue as it's by design.

**Closed by alena1108** 2019-10-17 05:27 UTC
Labels: kind/bug, team/ca
