### ISSUE TITLE
Failed to rotate expired certificates on an RKE cluster: unable to reach api server to fetch CA

### ISSUE THREAD

**Issue by hameno** [rancher/rke#1208] opened 2019-03-18 15:37 UTC
**RKE version:**
0.1.17
**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu, 4.15.0-43-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal, RKE
**cluster.yml file:**
n/a
**Steps to Reproduce:**
* Create cluster
* Wait one year
* Cry

**Results:**
Certificate expired (unnoticed on a weekend) after one year, control plane now broken, etc is logging:
etcdmain: rejected connection from "10.x.x.x:2580" (error "remote error: tls: bad certificate", ServerName "")

Tried renewing with 0.2.0-rc9 but only got this error: 
WARN[0000] This is not an officially supported version (v0.2.0-rc9) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
INFO[0000] Initiating Kubernetes cluster
INFO[0000] Rotating Kubernetes cluster certificates
FATA[0000] Failed to rotate certificates: can't find old certificates

**Comment by galal-hussein** [comment] 2019-03-18 16:19
@hameno can you provide more information about the running command, and full logs of rke

**Comment by hameno** [comment] 2019-03-18 16:24
Logs are complete for regenerate command, should I try with up?

**Comment by galal-hussein** [comment] 2019-03-18 16:28
@hameno I think rke up will fail as well, this might be a bug in here https://github.com/rancher/rke/blob/master/cmd/common.go#L148, where we only try to get old state from kubernetes, however we should also try to fetch the old certs/state from nodes

**Comment by galal-hussein** [comment] 2019-03-18 16:50
To reproduce the issue:

- run rke with v0.1
- docker stop kube-apiserver
- run rke rotate with v0.2
```
./rke cert rotate
WARN[0000] This is not an officially supported version (v0.0.12-dev) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest 
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [state] Possible legacy cluster detected, trying to upgrade 
INFO[0000] [reconcile] Rebuilding and updating local kube config 
INFO[0000] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml] 
INFO[0000] [state] Fetching cluster state from Kubernetes 
INFO[0030] Timed out waiting for kubernetes cluster to get state 
WARN[0030] [state] can't fetch legacy cluster state from Kubernetes 
INFO[0030] Rotating Kubernetes cluster certificates     
FATA[0030] Failed to rotate certificates: can't find old certificates
```

**Comment by alena1108** [comment] 2019-03-18 16:57
@hameno thanks for reporting the issue. We are addressing certificate expiration issue in Rancher 2.2 and RKE v0.2.0. The documentation will be published on the rancher website. 

We are also working on back porting certificate rotation to Rancher 2.0.x and 2.1.x.

**Comment by hameno** [comment] 2019-03-18 17:20
Thanks, so it should work for our still working cluster which expires at 4.9.

**Comment by galal-hussein** [comment] 2019-03-18 17:52
@hameno yes this should work normally for working clusters

**Comment by hameno** [comment] 2019-03-18 17:53
@galal-hussein Thanks, one question remains: How can I change the caCert of an imported cluster in rancher?

**Comment by alena1108** [comment] 2019-03-18 20:27
@hameno if you are coming from Rancher side, cert rotation is only available for the clusters launched from Rancher. In case the cluster was created using standalone RKE, and then imported into Rancher, the cert rotation should be done via standalone RKE.

Once the fix is tested, we are going to put an instructions to the RKE release notes on how to rotate the certs in cluster with a standalone RKE.

**Comment by hameno** [comment] 2019-03-18 20:28
@alena1108 Thanks, please see my comment in https://github.com/rancher/rke/pull/1211

**Comment by alena1108** [comment] 2019-03-18 21:10
@hameno : @galal-hussein is going to follow up with you to fetch more details on the setup. 

@sangeethah rke rc10 can be used to test the fix in house. @galal-hussein is going to provide you a custom binary to emulate the cluster where the cert expired in ~< 1 hour

**Comment by hameno** [comment] 2019-03-18 22:42
@galal-hussein helped me fix the cluster, looked like something specific to our setup

**Comment by galal-hussein** [comment] 2019-03-19 09:04
There is an issue with the service account token not being generated on legacy cluster and there for it has to be handled in the code when we fetch certs from nodes in case of expired setup

**Comment by galal-hussein** [comment] 2019-03-19 10:28
Summary of the problem:

The issue happen when rotating a **failed** old cluster (created by rke 0.1.x), i.e the kube-api is not reachable, here what happens:

- rke rotate tries to fetch the old certificates/state to create the cluster.rkestate file
- rke fails to fetch the certs/state and error out

The issue fix was to try to fetch certs/state from the nodes if k8s is not reachable, the fix worked however since this an old cluster `service-account-token-key.pem` wasn't generated, to resolve this we have to make sure when we fetch certs from the nodes that if  `service-account-token-key.pem` is missing then we create it and make it equal to kube-apiserver-key.pem so that no service-account-token would be invalidated.

PRS:

https://github.com/rancher/rke/pull/1211 - initial fix - merged
https://github.com/rancher/rke/pull/1213 - service account token handling - RFR

**Comment by sangeethah** [comment] 2019-03-19 15:15
Tested with v0.2.0-rc10

Deploy a cluster with certs that expire quickly.
Wait for the cert expiry.
```
MacBook-Pro-3:expired_cluster sangeethahariharan$ kubectl get nodes
Unable to connect to the server: x509: certificate has expired or is not yet valid
MacBook-Pro-3:expired_cluster sangeethahariharan$ pwd
```
Using RKE version - v0.2.0-rc10 rotate certs.
```
./rke cert rotate --config cluster.yml
```
Cert rotation reports success.
But canal pods get into bad state.

Following logs seens repeatedly in the pods:

```
E0319 03:46:25.437509       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:26.438794       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:27.440311       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:28.441740       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:29.443219       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:30.444638       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:31.446133       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:32.447585       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:33.449053       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:34.450693       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:35.452141       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:36.454351       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:37.455990       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:38.457514       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:39.459400       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:40.462288       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:41.463946       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:42.889253       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
E0319 03:46:43.893004       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:295: Failed to list *v1.Node: Unauthorized
```

**Comment by bmdepesa** [comment] 2019-03-19 19:42
rke 0.2.0-rc11

* Created RKE cluster
* Certs expired
* Rotate certs
* Cluster becomes accessible
* No errors in canal logs
* Ingress created before & after certs rotated have IP assigned and crosshost communication is functional

**Closed by bmdepesa** 2019-03-19 19:42 UTC
Labels: kind/bug, status/ready-for-review, status/reopened, status/resolved, status/to-test

**Comment by MSandro** [comment] 2019-06-24 07:21
I get the same error message:
`Failed to rotate certificates: can't find old certificates`
on my custom cluster after changing the rancher domain.

**Comment by pbaezab** [comment] 2019-09-24 15:58
> rke 0.2.0-rc11
> 
> * Created RKE cluster
> * Certs expired
> * Rotate certs
> * Cluster becomes accessible
> * No errors in canal logs
> * Ingress created before & after certs rotated have IP assigned and crosshost communication is functional

Hi, to me the process fire this step, Whats is this?
INFO[0000] [state] Possible legacy cluster detected, trying to upgrade

I cancel the operation.

Thanks
