### ISSUE TITLE
Calico not compatible with RHEL 8.4/Kernel 4.18

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#2898] opened 2022-04-04 20:47 UTC
**RKE version:**
RKE 1.3.2

 
**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 RHEL 8.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**
 
- Deploy 3 node cluster with `v1.20.12-rancher1-1` and CNI `Canal` 
- Run RKE up on the cluster
- Observe broken CNI, and other pods
 

**Actual behavior:**
CNI network is broken
the pod for `coreDNS` keeps crashing 

```
 NAMESPACE       NAME                                       READY   STATUS             RESTARTS   AGE
ingress-nginx   default-http-backend-6977475d9b-p8wvj      1/1     Running            92         175m
ingress-nginx   ingress-nginx-admission-create-6m77j       0/1     Completed          0          175m
ingress-nginx   ingress-nginx-admission-patch-txsqm        0/1     Completed          2          175m
ingress-nginx   nginx-ingress-controller-2s6tk             1/1     Running            1          175m
ingress-nginx   nginx-ingress-controller-txmc6             1/1     Running            1          175m
ingress-nginx   nginx-ingress-controller-znt2l             1/1     Running            1          175m
kube-system     calico-kube-controllers-7d5d95c8c9-hnrdm   1/1     Running            1          176m
kube-system     canal-96xfl                                2/2     Running            3          176m
kube-system     canal-cg5vs                                2/2     Running            2          176m
kube-system     canal-ztnxp                                2/2     Running            2          176m
kube-system     coredns-55b58f978-bg9sl                    0/1     CrashLoopBackOff   44         175m
kube-system     coredns-55b58f978-xzc9d                    0/1     Running            44         175m
kube-system     coredns-autoscaler-76f8869cc9-j86lc        1/1     Running            1          175m
kube-system     metrics-server-55fdd84cd4-647cq            0/1     Running            65         175m
kube-system     rke-coredns-addon-deploy-job-jtpql         0/1     Completed          0          176m
kube-system     rke-ingress-controller-deploy-job-vnrj6    0/1     Completed          0          175m
kube-system     rke-metrics-addon-deploy-job-9kgzf         0/1     Completed          0          175m
kube-system     rke-network-plugin-deploy-job-f9nqr        0/1     Completed          0          176m
```

**Expected behavior:**
CNI network is not broken
 

**More Info:**
"Kube-proxy codebase indicates that a module called "nf_conntrack_ipv4" is loaded based on the kernel version being less than 4.19: https://github.com/kubernetes/kubernetes/blob/master/pkg/util/ipvs/ipvs.go#L126 — it is unclear to me that iptables mode would relay on this kernel module.

This issue indicates that in RHEL 8.3+ (running kernel v4.18) the nf_conntrack_ipvs module has been merged into nf_conntrack: https://github.com/kubernetes/kubernetes/issues/97052

This may explain the warning message indicating a failure to load the nf_conntrack_ipv4 kernel module."
 
**Additional notes:**
Have not tested with other versions (k8s/docker/RKE) but I suspect this issue is present in 8.4 because of the kernel module backporting they did.

SURE-4290

**Comment by markusewalker** [comment] 2022-05-06 16:57
@jiaqiluo looked into this further on my end. I tested using RHEL 8.5 with kernel version `4.18.0-305.el8.x86_64`. I wasn't able to see this issue with `Canal` as my CNI. Please see below:

```
$ kubectl get nodes
NAME        STATUS   ROLES                      AGE   VERSION
mew-rhel1   Ready    controlplane,etcd,worker   14m   v1.22.9
mew-rhel2   Ready    controlplane,etcd,worker   14m   v1.22.9
mew-rhel3   Ready    controlplane,etcd,worker   14m   v1.22.9
```

```
$ kubectl get pods -A
NAMESPACE       NAME                                         READY   STATUS      RESTARTS   AGE
ingress-nginx   ingress-nginx-admission-create--1-lpbs7      0/1     Completed   0          14m
ingress-nginx   ingress-nginx-admission-patch--1-vglr9       0/1     Completed   0          14m
ingress-nginx   nginx-ingress-controller-fbgf8               1/1     Running     0          14m
ingress-nginx   nginx-ingress-controller-j8txt               1/1     Running     0          14m
ingress-nginx   nginx-ingress-controller-lp28s               1/1     Running     0          14m
kube-system     calico-kube-controllers-5685fbd9f7-jxvpl     1/1     Running     0          14m
kube-system     canal-dxc5w                                  2/2     Running     0          14m
kube-system     canal-kxb4l                                  2/2     Running     0          14m
kube-system     canal-r4z9p                                  2/2     Running     0          14m
kube-system     coredns-8578b6dbdd-sdcd2                     1/1     Running     0          14m
kube-system     coredns-8578b6dbdd-zbhvd                     1/1     Running     0          14m
kube-system     coredns-autoscaler-79dcc864f5-z5fp6          1/1     Running     0          14m
kube-system     metrics-server-6bc7854fb5-cv96x              1/1     Running     0          14m
kube-system     rke-coredns-addon-deploy-job--1-f627k        0/1     Completed   0          14m
kube-system     rke-ingress-controller-deploy-job--1-rplb5   0/1     Completed   0          14m
kube-system     rke-metrics-addon-deploy-job--1-cn422        0/1     Completed   0          14m
kube-system     rke-network-plugin-deploy-job--1-8x9z4       0/1     Completed   0          14m
```
I used `Calico` as the CNI and I received the same results as above as well. The differences, at least from the description, is that I am using RHEL 8.5 and `v1.22.9` as my version.

**Comment by HarrisonWAffel** [comment] 2022-05-06 17:33
@markusewalker, thanks for checking! It's likely this issue only occurs on RHEL 8.4 due to an issue described in this documentation: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/node-requirements/#oracle-linux-and-rhel-derived-linux-nodes . I've responded to the reporter in the related SURE issue and he has confirmed these prerequisite commands resolve the customers issue. Once we get a response from the customer this issue will be closed

**Comment by snasovich** [comment] 2022-05-12 14:23
Marking as Blocked since we're waiting for confirmation from the customer

**Comment by snasovich** [comment] 2022-05-26 02:20
This was confirmed as resolved by following the steps referenced in https://github.com/rancher/rke/issues/2898#issuecomment-1119840347. Closing the issue.

**Closed as completed** 2022-05-26 02:20 UTC
Labels: internal, team/area2, QA/S
