### ISSUE TITLE
Port check fails for network plugins

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#1102] opened 2019-01-27 23:40 UTC
**RKE version:**
master
**Docker version: (`docker version`,`docker info` preferred)**
all
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
all
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
all

**Steps to Reproduce:**
- rke up
- rke remove
- rke up again

**Results:**

Network port check fails for canal and the rest of the network plugins
```
FATA[0042] [[network] Host [52.39.29.233] is not able to connect to the following ports: [x.x.x.x (x.x.x.x:8472) open, y.y.y.y (y.y.y.y:8472) open, z.z.z.z (z.z.z.z:8472) open]. Please check network policies and firewall rules] 
```

**Comment by guangbochen** [comment] 2019-01-28 12:43
Because UDP is connectionless, so it has no acknowledgment, retransmission, or timeout, and we cannot reliably distinguish an open port from a firewalled port or from a lost packet.

With either AWS or GCP, the state will always be `false` when the UDP port `8472` is opened in our network-security group. 
```
ubuntu@ip-hostip:~$ sudo nmap -sU -p $hostip

Starting Nmap 7.60 ( https://nmap.org ) at 2019-01-28 11:29 UTC
Nmap scan report for ec2-$hostip.ap-northeast-1.compute.amazonaws.com ($hostip)
Host is up (0.00038s latency).

PORT     STATE  SERVICE
8472/udp closed otv

Nmap done: 1 IP address (1 host up) scanned in 0.55 seconds
```

and the state is changed to `open|filtered` if the `UDP` port `8472`  is disabled in the network-security group.

```
ubuntu@ip-hostip:~$ sudo nmap -sU -p $hostip

Starting Nmap 7.60 ( https://nmap.org ) at 2019-01-28 11:29 UTC
Nmap scan report for ec2-$hostip.ap-northeast-1.compute.amazonaws.com ($hostip)
Host is up (0.00040s latency).

PORT     STATE         SERVICE
8472/udp open|filtered otv

Nmap done: 1 IP address (1 host up) scanned in 0.56 seconds
```
Lastly, regardless the `8472` UDP port of the network security group is opened or disabled, its state will always be `open|filtered`  once the k8s network plugin like `flannel` is installed in the host machine.

And that's the reason why our original port check rules like `nc -w5 -uzv $host $por` is not working as expected for an installed k8s cluster, the `nc` or `nmap` for udp port check is flawed, and things like `rke remove` will not completely clean up the existing network plugin with udp port `8472` without a system reboot. 

So It is hard to for us to determine whether the udp port `8472` is closed or opened by the firewall, and we have to disable the `UDP` port check for now.

**Comment by galal-hussein** [comment] 2019-01-28 18:07
@guangbochen i think there is another problem also with the network plugin check, i can see that you are calling the check from 4 different places which causes a big delay to the installation path, however it should only be called once.

**Comment by alena1108** [comment] 2019-01-29 04:31
Should work now as the original port check fix has been reverted

**Comment by sangeethah** [comment] 2019-02-05 22:38
Tested with rke version - v0.2.0-rc5

This issue is not reproducible anymore.
Able to do the following steps mutliple times and get a 3 node cluster up and running:
```
* rke up
* rke remove
* rke up again
```

**Closed by sangeethah** 2019-02-05 22:38 UTC
Labels: kind/bug, priority/0, status/reopened, status/resolved, status/to-test
