### ISSUE TITLE
User provided CA cert/key

### ISSUE THREAD

**Issue by lmickh** [rancher/rke#586] opened 2018-05-07 21:06 UTC
**RKE version:**
v0.1.6

**Enhancement**
Allow users to provide the CA cert/key that is then used to generate the rest of the certificates.  This allows the user to leverage their existing CA trust chains across the Rancher/RKE clusters.  I would imagine it looking something like when providing etcd certs in the `cluster.yml`.   The existing pki code would have to check for the value before defaulting to generating the CA instead of the current implementation.

**Comment by galal-hussein** [comment] 2018-05-07 21:46
@lmickh thanks for opening the issue, this is a duplicate of https://github.com/rancher/rke/issues/450

**Closed by galal-hussein** 2018-05-07 21:46 UTC
