### ISSUE TITLE
rke snapshot-restore brings 502 Bad Gateway

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rke#637] opened 2018-05-18 17:14 UTC
Hi,
here is my steps:
1. installing rke with HA version: 1 nginx, 3 etcd, 3 controplane, 3 worker (`./rke_linux-amd64 up --config rancher-cluster.yml` (https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/)
2. creating deployment with a few replicas(for test purposes)
3. creating etcd backup `./rke_linux-amd64 etcd snapshot-save --name snapshot --config rancher-cluster.yml`
4. removing my cluster in order to test the restore of etcd `./rke_linux-amd64 remove --config rancher-cluster.yml` and then removing all containers and images from hosts separately: 
```./cleanup.sh ; docker stop `docker ps |awk '{print $1}' |paste -sd' '` ; docker rm `docker ps -a |awk '{print $1}' |paste -sd' '` ; docker rmi `docker images |awk '{print $3}' |paste -sd' '` ; service docker stop && rm -rf /var/lib/docker/ ; umount -l -f /var/lib/rancher/volumes/ ; umount -l -f /var/lib/rancher ; rm -rf /var/lib/rancher ; umount -l -f /var/lib/kubelet ; service docker start && docker ps```
I've downloaded the./cleanup.sh script from @superseb repo (https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d)
4. installing the rke with the same way/config as I've described in the 1st step
5. coping the saved snapshot to all etcd hosts in the `/opt/rke/etcd-snapshots/` directory
6. restoring from snapshot `./rke_linux-amd64 etcd snapshot-restore --name snapshot --config rancher-cluster.yml `
7. get 502 Bad Gateway :(
also the pods aren't recreated after delete

```
kubectl get po --all-namespaces --show-all
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
cattle-system   cattle-84f9cd8589-j7nl2                   1/1       Running     0          4h
cattle-system   cattle-cluster-agent-7657c8c794-rw9k4     1/1       Running     0          4h
cattle-system   cattle-node-agent-2mvhd                   1/1       Running     0          4h
cattle-system   cattle-node-agent-bp872                   1/1       Running     0          4h
cattle-system   cattle-node-agent-flvkt                   1/1       Running     0          4h
default         ubuntutest-94846979c-85g4b                1/1       Running     0          4h
default         ubuntutest-94846979c-bgbp9                1/1       Running     0          4h
default         ubuntutest-94846979c-hsr58                1/1       Running     0          4h
default         ubuntutest-94846979c-vshb5                1/1       Running     0          4h
ingress-nginx   default-http-backend-564b9b6c5b-7qbtm     1/1       Running     0          4h
ingress-nginx   nginx-ingress-controller-cm7ht            1/1       Running     0          4h
ingress-nginx   nginx-ingress-controller-cwhg8            1/1       Running     0          4h
ingress-nginx   nginx-ingress-controller-g5877            1/1       Running     0          4h
kube-system     canal-mcl6t                               3/3       Running     1          4h
kube-system     canal-nknjq                               3/3       Running     0          4h
kube-system     canal-ntl9w                               3/3       Running     0          4h
kube-system     kube-dns-5ccb66df65-j6q5f                 3/3       Running     0          4h
kube-system     kube-dns-autoscaler-6c4b786f5-87l85       1/1       Running     0          4h
kube-system     rke-ingress-controller-deploy-job-ctjgb   0/1       Completed   0          4h
kube-system     rke-kubedns-addon-deploy-job-f85zk        0/1       Completed   0          4h
kube-system     rke-network-plugin-deploy-job-6sjqx       0/1       Completed   0          4h
kube-system     rke-user-addon-deploy-job-v5xpk           0/1       Completed   0          4h
```

**Comment by Lssikkes** [comment] 2018-05-28 11:32
I'm seeing the same thing, using rke v0.1.7.
Cluster nginx will not show "default backend - 404" on a wrong domain, but 502 Bad Gateway after a snapshot restore.

**Comment by harutyundermenjyan** [comment] 2018-06-05 12:45
seem the issue doesn't resolved,
now the web interface doesn't reachable at all after etcd restore.

**Comment by harutyundermenjyan** [comment] 2018-06-05 18:39
@galal-hussein any update?

**Comment by harutyundermenjyan** [comment] 2018-06-06 08:06
```
kubectl get po --all-namespaces
NAMESPACE       NAME                                      READY     STATUS             RESTARTS   AGE
cattle-system   cattle-84f9cd8589-wmrzk                   1/1       Running            0          19h
cattle-system   cattle-cluster-agent-556bdc4698-z55zp     1/1       Running            3          19h
cattle-system   cattle-node-agent-2lhnq                   0/1       Error              6          19h
cattle-system   cattle-node-agent-c9g62                   0/1       CrashLoopBackOff   6          19h
cattle-system   cattle-node-agent-v65j2                   0/1       CrashLoopBackOff   6          19h
default         ubuntutest-94846979c-fndnm                1/1       Running            0          5m
default         ubuntutest-94846979c-s4wb4                1/1       Running            0          19h
default         ubuntutest-94846979c-v28cj                1/1       Running            0          19h
ingress-nginx   default-http-backend-564b9b6c5b-kmv8z     1/1       Running            1          19h
ingress-nginx   nginx-ingress-controller-fp7zt            0/1       CrashLoopBackOff   6          19h
ingress-nginx   nginx-ingress-controller-pj6fn            0/1       CrashLoopBackOff   6          19h
ingress-nginx   nginx-ingress-controller-vhpj6            0/1       CrashLoopBackOff   6          19h
kube-system     canal-dhspz                               1/3       CrashLoopBackOff   8          2m
kube-system     canal-k8rj8                               1/3       CrashLoopBackOff   8          2m
kube-system     canal-rslpt                               1/3       CrashLoopBackOff   8          2m
kube-system     kube-dns-5ccb66df65-gsskw                 2/3       Running            8          19h
kube-system     kube-dns-autoscaler-6c4b786f5-mck8q       1/1       Running            0          19h
kube-system     rke-ingress-controller-deploy-job-bhfnt   0/1       Completed          0          19h
kube-system     rke-kubedns-addon-deploy-job-jp4mt        0/1       Completed          0          19h
kube-system     rke-network-plugin-deploy-job-gjbhp       0/1       Completed          0          19h
kube-system     rke-user-addon-deploy-job-bp4sn           0/1       Completed          0          19h
```

**Comment by harutyundermenjyan** [comment] 2018-06-08 07:28
now it exit with the following error at the restore time:
`FATA[0022] Failed to run certificate bundle extract, exit status is: 1`

**Comment by shyam** [comment] 2018-06-13 15:12
+1

I'm also facing the same issue. 

**RKE version:**
````
rke version v0.1.7
````
**Docker version: (`docker version`,`docker info` preferred)**

````
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
````
````
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.5 GiB
Name: test-k8s-etcd03.testserver.de
ID: WUPV:FGNH:XKTY:SFS2:YY54:KXNV:D2DR:ATCO:NBTP:56A5:SLLP:LXCF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
````
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

````
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
````
`4.4.0-116-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

````
#  RKE environment 01

# x.y.205.235  test-k8s-master01.testserver.de test-k8s-master01
# x.y.205.243  test-k8s-master02.testserver.de test-k8s-master02
# x.y.205.135  test-k8s-master03.testserver.de test-k8s-master03
# x.y.205.50   test-k8s-etcd03.testserver.de test-k8s-etcd03
# x.y.205.80   test-k8s-etcd01.testserver.de test-k8s-etcd01
# x.y.205.75   test-k8s-worker03.testserver.de test-k8s-worker03
# x.y.205.61   test-k8s-worker02.testserver.de test-k8s-worker02

nodes:
- address: x.y.205.235
  port: "22"
  internal_address: x.y.205.235
  role:
  - controlplane
  - etcd
  hostname_override: test-k8s-master01.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    app: ingress
- address: x.y.205.243
  port: "22"
  internal_address: x.y.205.243
  role:
  - controlplane
  - etcd
  hostname_override: test-k8s-master02.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    app: ingress
- address: x.y.205.135
  port: "22"
  internal_address: x.y.205.135
  role:
  - controlplane
  - etcd
  hostname_override: test-k8s-master03.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    app: ingress
- address: x.y.205.50
  port: "22"
  internal_address: x.y.205.50
  role:
  - etcd
  hostname_override: test-k8s-etcd03.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
- address: x.y.205.80
  port: "22"
  internal_address: x.y.205.80
  role:
  - etcd
  hostname_override: test-k8s-etcd01.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
- address: x.y.205.75
  port: "22"
  internal_address: x.y.205.75
  role:
  - worker
  hostname_override: test-k8s-worker03.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
- address: x.y.205.61
  port: "22"
  internal_address: x.y.205.61
  role:
  - worker
  hostname_override: test-k8s-worker02.testserver.de
  user: ops
  ssh_key_path: "~/.ssh/nonprod"
  labels:
    node_class: "general_purpose"
services:
  etcd:
    image: rancher/coreos-etcd:v3.1.12
    extra_args: {}
    extra_binds: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
    service_cluster_ip_range: 10.143.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
    cluster_cidr: 10.142.0.0/16
    service_cluster_ip_range: 10.143.0.0/16
  scheduler:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
  kubelet:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {"cgroup-driver":"systemd","fail-swap-on":"false"}
    extra_binds: []
    cluster_domain: testserver.de
    infra_container_image: rancher/pause-amd64:3.1
    cluster_dns_server: 10.143.0.10
    fail_swap_on: false
  kubeproxy:
    image: rancher/hyperkube:v1.10.3-rancher2
    extra_args: {}
    extra_binds: []
network:
  plugin: flannel
  options: {}
authentication:
  strategy: x509
  options: {}
  sans:
    - "test-rke01-master-lb01.testserver.de"
    - "test-rke01-master-lb02.testserver.de"
    - "test-rke01-master-lb.testserver.de"
addons: ""
addons_include: []
ssh_key_path: "~/.ssh/nonprod"
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: "nginx"
  node_selector:
    app: ingress
cluster_name: "test-rke01"
cloud_provider:
  name: ""
  cloud_config: {}
prefix_path: ""
addon_job_timeout: 30
````
**Steps to Reproduce:**

1. Run `rke up` to create the cluster.
2. Create a deployment which deploys some pods across nodes and exposes it as service and ingress.
3. Visit the host set up on ingress ( entries in /etc/hosts may be necessary ). It works.
4. Perform Etcd snapshot by running `rke etcd snapshot-save`
5. Backup `kube_config_cluster.yml` as `kube_config_cluster.yml.backup` 
6. Remove the cluster and cleanup using the gist from @superseb repo ( https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d ) and reboot.
7. Recreate the cluster using `rke up` command.
8. Rename the snapshots as "snapshot" `under /opt/rke/etcd-snapshots` on all nodes under etcd plane.
9. Restore Etcd Snapshot by running `rke etcd snapshot-restore --name snapshot`
10. Restore the earlier `kube_config_cluster.yml` from the `kube_config_cluster.yml.backup`
11. Run `rke up` again.
12. Verify if pods, ingress are running.
13. Visiting the ingress will result in 502 Bad Gateway.

**Comment by harutyundermenjyan** [comment] 2018-06-14 09:03
@deniseschannon 
The issue still exists.
I've tested it with rke v0.1.8-rc2.

**Comment by superseb** [comment] 2018-06-14 09:20
As long as the issue is open, it is under investigation/testing. There is no point in pinging people directly about issues until the issue is closed as solved/released.

**Comment by harutyundermenjyan** [comment] 2018-06-14 11:44
just wanted to remind and inform that I've tested it with the new released rke as well.

**Comment by soumyalj** [comment] 2018-06-26 00:06
Tested with rke version v0.1.8-rc5.
1. Run rke up to create HA cluster. 
[https://raw.githubusercontent.com/rancher/rancher/e9d29b3f3b9673421961c68adf0516807d1317eb/rke-templates/3-node-certificate-recognizedca.yml]
2. Perform Etcd snapshot by running rke etcd snapshot-save
3. Backup kube_config_cluster.yml as kube_config_cluster.yml.backup
4. Remove the cluster and cleanup using the gist from @superseb repo ( https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d ) and reboot.
5. Recreate the cluster using rke up command.
6. Rename the snapshots as "snapshot" under /opt/rke/etcd-snapshots on all nodes under etcd plane.
7. Restore Etcd Snapshot by running rke etcd snapshot-restore --name snapshot
8. Restore the earlier kube_config_cluster.yml from the kube_config_cluster.yml.backup
9. Run rke up again.

rke up fails with a panic as below :
```
INFO[0102] [remove/rke-log-linker] Successfully removed container on host [abc] 
INFO[0102] [remove/rke-log-linker] Successfully removed container on host [def] 
INFO[0102] [worker] Successfully started Worker Plane.. 
INFO[0102] [sync] Syncing nodes Labels and Taints       
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b0ae41]

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc4206fe4c8)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x28d
panic(0x1f38f40, 0x2a24b40)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rke/k8s.SyncTaints(0xc420d4a820, 0xc4202679e0, 0xe, 0x2a5a248, 0x0, 0x0, 0x2a5a248, 0x0, 0x0, 0xc420b32540, ...)
	/go/src/github.com/rancher/rke/k8s/node.go:161 +0x161
github.com/rancher/rke/cluster.(*Cluster).SyncLabelsAndTaints(0xc420459800, 0x29c81e0, 0xc4200743f0, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cluster/cluster.go:329 +0x35d
github.com/rancher/rke/cmd.ClusterUp(0x29c81e0, 0xc4200743f0, 0xc42006c700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/up.go:125 +0x4b7
github.com/rancher/rke/cmd.clusterUpFromCli(0xc420040140, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cmd/up.go:184 +0x332
reflect.Value.call(0x1ed2300, 0x2172b68, 0x13, 0x20e23f3, 0x4, 0xc4205bc468, 0x1, 0x1, 0xc4205bc3f0, 0x20a95a0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x1ed2300, 0x2172b68, 0x13, 0xc4205bc468, 0x1, 0x1, 0x140, 0xc420040140, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x1ed2300, 0x2172b68, 0xc420040140, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x198
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x20e1b01, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20f7ac6, 0x14, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0xab8
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc420240000, 0xc42007c080, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x5d6
main.mainErr(0x1dbb576, 0xc4205bdf68)
	/go/src/github.com/rancher/rke/main.go:45 +0x163f
main.main()
	/go/src/github.com/rancher/rke/main.go:14 +0x22

```

**Comment by galal-hussein** [comment] 2018-06-26 19:47
@soumyalj regarding your latest test case, in step 5:
```
Recreate the cluster using rke up command.
```
this is not correct, this makes the certificate bundle fix useless because you basically ran rke up before restore so certificates will be regenerated and restoration process won't work.

what you need to do is restore first then run `rke up`

The panic is was just a bug that i put a fix for it, but you need to retest with the above notes.

**Comment by harutyundermenjyan** [comment] 2018-06-28 17:28
rke v0.1.8-rc8
now, after restoration of `etcd` and run `rke up` it fails with:
```
INFO[0021] [addons] Executing deploy job.. 
ERRO[0082] [k8s] Job [rke-network-plugin-deploy-job] is not deleted 
FATA[0082] [k8s] Job [rke-network-plugin-deploy-job] is not deleted 
```
but with rke `v0.1.8-rc5` it doesn't fail and completes successfully.

**Comment by galal-hussein** [comment] 2018-06-29 00:58
@soumyalj fixed the timing issue that caused the problem and i was able to do the full restoring process successfully, you can restest with v0.1.8-rc9

**Comment by harutiundermenjian** [comment] 2018-06-29 07:35
rke v0.1.8-rc9
I've tried to restore my old backup did by v0.1.8-rc5 if I remember it right but rke up failed as below:
Restoration process finished successfully but rke up failed.
```
./rke_linux-amd64 etcd snapshot-restore ....
INFO[0000] Starting restoring snapshot on etcd hosts    
INFO[0021] Finished restoring snapshot [snapshot] on all etcd hosts 
```
```
./rke up ...
INFO[0000] Building Kubernetes cluster    
INFO[0257] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin 
INFO[0257] [addons] Executing deploy job..              
ERRO[0340] Failed to get job complete status: <nil>     
FATA[0340] Failed to get job complete status: <nil>     
```

**Comment by galal-hussein** [comment] 2018-06-29 18:39
@harutyundermenjyan @harutiundermenjian I wasn't able to reproduce, i tried taking a backup with 0.1.8-rc5 and restored with the latest rc and i can restore normally and rke up finished successfully.
It maybe originally a problem with the addon after restarting the k8s components like its mentioned here in step 7 https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/, try to delete the addon jobs
```
kubectl delete jobs all -n kube-system
```
and run rke up again

@soumyalj can you proceed with testing the issue.

**Comment by soumyalj** [comment] 2018-06-30 02:43
Tested with rke version v0.1.8-rc10

1. Run rke up to create HA cluster. Create some pods
[https://raw.githubusercontent.com/rancher/rancher/e9d29b3f3b9673421961c68adf0516807d1317eb/rke-templates/3-node-certificate-recognizedca.yml]
2. Perform Etcd snapshot by running rke etcd snapshot-save and copy the snapshot  and certificate bundle to another host h1 (not in the cluster)
3. Remove the cluster and cleanup using the gist from @superseb repo ( https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d ) and reboot. Cleanup /opt/rke/etcd-snapshots directory
4. Copy the snapshot and certificate bundle from h1 to each of the nodes in the HA cluster
5. Restore Etcd Snapshot by running ` rke etcd snapshot-restore --name snapshot --config cluster.yml`
6. Run rke up again.

rke up was successful and HA cluster was functional. The pods in the cluster were intact. Creation of new pods was also successful

**Closed by soumyalj** 2018-06-30 02:43 UTC
Labels: bug, resolved, to-test

**Comment by harutyundermenjyan** [comment] 2018-07-01 19:19
@galal-hussein Maybe I used a wrong certificate bundle not sure.
The restore works good with my other snapshots.
Thanks for all this process and solution.

**Comment by techcto** [comment] 2018-07-11 16:20
HI all, are we saying that you now have to remove the cluster / clean the cluster before uploading the snapshots and then executing the restore command?  Is there any way to just restore a working cluster?

Right now, I have 3 instances.  I run snapshot, I login to one of the servers and copy the snapshot to the other two servers.  I run restore and I get this error:

INFO[0016] [etcd] Successfully started [etcd-restore] container on host [*]
FATA[0016] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3
Command '['/tmp/bin/rke', 'etcd', 'snapshot-restore', '--name', 'etcdsnapshot_restore', '--config', '/tmp/config.yaml']' returned non-zero exit status 1

And on that host, I see this in the logs for rke-tools, I get:

time="2018-07-11T16:18:39Z" level=warning msg="Couldn't parse backup" error="parsing time \"etcdsnapshot\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"etcdsnapshot\" as \"2006\"" name=etcdsnapshot 
time="2018-07-11T16:18:39Z" level=warning msg="Couldn't parse backup" error="parsing time \"etcdsnapshot\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"etcdsnapshot\" as \"2006\"" name="etcdsnapshot_restore" 
time="2018-07-11T16:18:39Z" level=warning msg="Couldn't parse backup" error="parsing time \"pki.bundle.tar.gz\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"pki.bundle.tar.gz\" as \"2006\"" name=pki.bundle.tar.gz

**Comment by techcto** [comment] 2018-07-25 21:39
HI all, I found my way here.  It seems with a new set of servers and rke v0.1.9-rc2 I am able to successfully restore and do an up.  However, all looks good from command line using RKE, but my browser is stuck at 502 Bad Gateway.  Any idea where to look for error?  I can run up several times in a row and it always states: INFO[0041] Finished building Kubernetes cluster successfully.
