### ISSUE TITLE
Rke deployment job fails if specified ingress: options

### ISSUE THREAD

**Issue by arindamdat** [rancher/rke#870] opened 2018-08-20 11:31 UTC
**RKE version:**
v0.1.8
**Docker version: (`docker version`,`docker info` preferred)**
18.06.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal
**cluster.yml file:**
<pre>
ignore_docker_version: true
nodes:
  - address: 10.10.1.12
    user: admin.gubra
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa
    labels:
     workload: rancher-server
  - address: 10.10.1.5
    user: admin.gubra
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa
    labels:
     workload: application
  - address: 10.10.1.6
    user: admin.gubra
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
    labels:
     workload: application
  - address: 10.10.1.11
    user: admin.gubra
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
    labels:
     workload: ci
ingress:
    provider: nginx
    options:
       use-proxy-protocol: "true"
    extra_args:
      sort-backends: ""
</pre>
**Steps to Reproduce:**
./rke --config cluster.yaml
**Results:**
Cluster is created, but deployment job fails.

**Comment by galal-hussein** [comment] 2018-08-27 20:03
i wasn't able to reproduce the problem, i used the same yaml file and i can see ingress controller being deployed successfully:
ingress controller yaml
```
> kubectl get pod nginx-ingress-controller-674vx -n ingress-nginx -o yaml
  containers:
  - args:
    - /nginx-ingress-controller
    - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
    - --configmap=$(POD_NAMESPACE)/nginx-configuration
    - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
    - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
    - --annotations-prefix=nginx.ingress.kubernetes.io
    - --sort-backends
```

configmap yaml:
```
> kubectl get configmap nginx-configuration -n ingress-nginx -o yaml
apiVersion: v1
data:
  use-proxy-protocol: "true"
kind: ConfigMap
...
```

**Comment by arindamdat** [comment] 2018-08-28 13:44
Thanks @galal-hussein . I'll check it.

**Comment by galal-hussein** [comment] 2018-09-04 19:42
@arindamdat i will close the issue because i still can't reproduce it, if you still experiencing the problem please reopen

**Closed by galal-hussein** 2018-09-04 19:42 UTC
Labels: bug
