### ISSUE TITLE
Provision K8s cluster with --cloud-provider:openstack

### ISSUE THREAD

**Issue by wayarmy** [rancher/rke#281] opened 2018-01-29 03:56 UTC
Hi there,

I used rke 0.1.0 for installing k8s on my own Openstack system. But i can't find the way to provision k8s cluster with config cloud-provider. Can you provide for me the way to setup that cluster?

I've just patch rke cli with cloud-provider like this:
```
		Entrypoint: []string{"/opt/rke/entrypoint.sh",
			"kube-controller-manager",
			"--address=0.0.0.0",
			"--cloud-provider=openstack",
			"--leader-elect=true",
			"--kubeconfig=" + pki.KubeControllerConfigPath,
			"--enable-hostpath-provisioner=false",
			"--node-monitor-grace-period=40s",
			"--pod-eviction-timeout=5m0s",
			"--v=2",
			"--allocate-node-cidrs=true",
			"--cluster-cidr=" + kubeControllerService.ClusterCIDR,
			"--service-cluster-ip-range=" + kubeControllerService.ServiceClusterIPRange,
			"--service-account-private-key-file=" + pki.KubeAPIKeyPath,
			"--root-ca-file=" + pki.CACertPath,
			"--cloud-config=/etc/kubernetes/cloud.conf",
```
But i have got an errror:
```
INFO[0038] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-kubedns-addon 
INFO[0038] [addons] Executing deploy job..              
Failed to get job complete status: <nil>
FATA[0063] Failed to deploy addon execute job: Failed to get job complete status: <nil> 
```

And my controler container's logs:
```
I0129 03:53:29.183253       1 event.go:218] Event(v1.ObjectReference{Kind:"Job", Namespace:"kube-system", Name:"rke-kubedns-addon-deploy-job", UID:"95561c96-04a3-11e8-afd3-fa163e9f7086", APIVersion:"batch", ResourceVersion:"98534", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: rke-kubedns-addon-deploy-job-s9mln
I0129 03:53:29.295207       1 event.go:218] Event(v1.ObjectReference{Kind:"Job", Namespace:"kube-system", Name:"rke-network-plugin-deploy-job", UID:"9051f30d-03ec-11e8-afd3-fa163e9f7086", APIVersion:"batch", ResourceVersion:"3715", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: rke-network-plugin-deploy-job-rxxvk
I0129 03:53:39.178649       1 gc_controller.go:162] Found orphaned Pod rke-kubedns-addon-deploy-job-s9mln assigned to the Node 10.5.9.4. Deleting.
I0129 03:53:39.178674       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:rke-kubedns-addon-deploy-job-s9mln
I0129 03:53:39.187643       1 gc_controller.go:166] Forced deletion of orphaned Pod rke-kubedns-addon-deploy-job-s9mln succeeded
I0129 03:53:39.187675       1 gc_controller.go:162] Found orphaned Pod rke-network-plugin-deploy-job-rxxvk assigned to the Node 10.5.9.4. Deleting.
I0129 03:53:39.187680       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:rke-network-plugin-deploy-job-rxxvk
I0129 03:53:39.188046       1 event.go:218] Event(v1.ObjectReference{Kind:"Job", Namespace:"kube-system", Name:"rke-kubedns-addon-deploy-job", UID:"95561c96-04a3-11e8-afd3-fa163e9f7086", APIVersion:"batch", ResourceVersion:"98534", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: rke-kubedns-addon-deploy-job-fxw4p
I0129 03:53:39.192692       1 gc_controller.go:166] Forced deletion of orphaned Pod rke-network-plugin-deploy-job-rxxvk succeeded
I0129 03:53:39.299537       1 event.go:218] Event(v1.ObjectReference{Kind:"Job", Namespace:"kube-system", Name:"rke-network-plugin-deploy-job", UID:"9051f30d-03ec-11e8-afd3-fa163e9f7086", APIVersion:"batch", ResourceVersion:"3715", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: rke-network-plugin-deploy-job-q522g
```
And the logs of kubelet container:
```
I0129 03:53:52.435367    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:53:55.566320    5003 qos_container_manager_linux.go:320] [ContainerManager]: Updated QoS cgroup configuration
I0129 03:54:02.813300    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:54:13.215177    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:54:23.682931    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:54:34.303768    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:54:44.779269    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:54:55.237945    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:54:55.566727    5003 qos_container_manager_linux.go:320] [ContainerManager]: Updated QoS cgroup configuration
I0129 03:55:05.927141    5003 openstack_instances.go:46] Claiming to support Instances
I0129 03:55:16.391987    5003 openstack_instances.go:46] Claiming to support Instances
```

Any idea else for this ? I believe that error is cause of k8s-image of rancher: `rancher/k8s:v1.8.5-rancher4`

**Comment by alancivita** [comment] 2018-01-29 22:26
see issue #102  cloud providers are not supported yet.

**Comment by wayarmy** [comment] 2018-01-30 09:54
@alancivita thanks, but can you show me the Dockerfile of image `rancher/k8s:v1.8.5-rancher4`. Maybe i can find the way to workaround for this.

**Comment by galal-hussein** [comment] 2018-01-30 16:13
@wayarmy thanks for opening this issue, @alancivita is correct as rke doesn't officially support cloud providers yet, we hardcoded cloudproivder to components to `""` https://github.com/rancher/rke/blob/master/services/kubelet.go#L44, some users tried to override this parameter in all components using `extra_args` however i am not sure if that will work also you will need to place your provider configuration on the host manually inside `/etc/kubernetes`

**Comment by HighwayofLife** [comment] 2018-02-08 00:15
Just a note for anyone coming to this ticket later... having the ability to provide a cloud provider will be super helpful, and would allow for the ability to create cross-cloud clusters.

**Comment by superseb** [comment] 2018-02-08 12:08
Closing as duplicate of #102, we'll be following up in there.

**Closed by superseb** 2018-02-08 12:08 UTC
