### ISSUE TITLE
[feature] Support Custom CoreDNS Corefile

### ISSUE THREAD

**Issue by ekristen** [rancher/rke#1696] opened 2019-10-14 14:53 UTC
**RKE version:** 0.3.0

I add custom changes to the Corefile but whenever I upgrade the cluster all those changes get wiped out and I have to go add them back in. Being able to support either overriding the default Corefile or supplementing it as part of RKE would be very valuable, it would allow making changes to core cluster and keeping them in tact through upgrades.

**Comment by superseb** [comment] 2019-10-14 15:23
Duplicate of https://github.com/rancher/rke/issues/1645

**Closed by superseb** 2019-10-14 15:23 UTC
