### ISSUE TITLE
The kubernetes_version value is often ignored

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#1049] opened 2018-12-04 06:17 UTC
**RKE version:**
v0.1.12

**Docker version: (`docker version`,`docker info` preferred)**
```
root@dnoland-rke1:~# docker version; docker info
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64
 Experimental: false
Containers: 35
 Running: 23
 Paused: 0
 Stopped: 12
Images: 21
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 175
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1049-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: dnoland-rke1
ID: YTVP:2C3F:G4RA:QV65:DPTL:KFVH:2MXG:PBQU:MI5K:MLHQ:IFPC:NKBO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
root@dnoland-rke1:~# cat /etc/os-release ; uname -r
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-1049-aws
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```
$ cat cluster.yml
---
bastion_host:
    address: 35.166.126.198
    user: ubuntu

authentication:
    sans:
      - "35.166.126.198"

kubernetes_version: v1.11.1-rancher1-1

nodes:
  - address: 10.0.0.20
    hostname_override: dnoland-rke1
    user: ubuntu
    role:
    - controlplane
    - etcd
    - worker

ssh_agent_auth: true

ignore_docker_version: true
```
**Steps to Reproduce:**
Run rke up, run kubectl get nodes --kubeconfig=kube_config_cluster.yml, rke remove. Repeat for different values in `kubernetes_version`

**Results:**

v1.12.1-rancher1-1
```
NAME           STATUS   ROLES                      AGE   VERSION
dnoland-rke1   Ready    controlplane,etcd,worker   96s   v1.12.1
```
v1.12.0-rancher1-1
```
NAME           STATUS   ROLES                      AGE   VERSION
dnoland-rke1   Ready    controlplane,etcd,worker   1m    v1.11.3
```
v1.11.2-rancher1-2
```
NAME           STATUS   ROLES                      AGE   VERSION
dnoland-rke1   Ready    controlplane,etcd,worker   2m    v1.11.3
```
v1.11.1-rancher1-1
```
NAME           STATUS   ROLES                      AGE   VERSION
dnoland-rke1   Ready    controlplane,etcd,worker   58s   v1.11.3
```

**Comment by superseb** [comment] 2018-12-04 23:16
I believe the problem here is in https://github.com/rancher/rke/blob/v0.1.12/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L610. 

The available versions are limited to the versions in `k8sVersionsCurrent`. Which explains when you enter a valid Kubernetes version for that RKE CLI version, it will be applied. 

Else it will default to the default set in the vendored types for that RKE CLI version: https://github.com/rancher/rke/blob/v0.1.12/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L12

**Comment by alena1108** [comment] 2018-12-04 23:31
@superseb @dnoland1 we should be careful when fixing this issue. Arbitrary version might require extra parameters - that can be either defined in rke or in types - to be passed in. Ideally we should document what k8s versions are supported by a particular rke version, and if the version user wants to upgrade to is not a part of the installed rke, user should upgrade to the latest.

**Comment by alena1108** [comment] 2018-12-21 23:18
As a part of this fix, we should make sure that 1.9 is the min version we support in the latest rke.

**Comment by vikas027** [comment] 2018-12-31 09:57
Looks like this is fixed in `rke version v0.1.14`. I've specified `kubernetes_version: "v1.12.3-rancher1-1"` in the `cluster.yml` file and things look good to me

```
🍺  $ kubectl version --short
Client Version: v1.10.3
Server Version: v1.12.3
🍺  $
```

**Comment by SergeyNosko** [comment] 2019-01-09 14:39
Desired kubernetes_version - v1.12.3-rancher1-1.
This version present at both versions - v0.1.14 and v0.1.15:

rke v0.1.14 - respects kubernetes_version at yaml config
rke v0.1.15 - doesn't respect kubernetes_version at yaml config and installs v1.11.6-rancher1-1


`https://github.com/rancher/rke/blob/v0.1.14/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L12`

and 

`https://github.com/rancher/rke/blob/v0.1.15/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L12`

**Comment by alena1108** [comment] 2019-01-25 18:08
Can be tested in `v0.2.0-rc4` rke

**Comment by soumyalj** [comment] 2019-02-08 22:40
Reproduced the issue with rke version v0.1.12. Kubernetes versions provided are ignored.

Tested with rke version v0.2.0-rc5. 
Create a cluster using rke up command with k8s version v1.11.1-rancher1-1. Nodes get displayed correctly with k8s version v1.11.1
Change the version to v1.11.5-rancher1-1 and do rke up again . The version gets displayed correctly with v1.11.5. 
```
$ kubectl get node --kubeconfig kube_config_cluster.yml
NAME             STATUS    ROLES                      AGE       VERSION
abcd   Ready     controlplane,etcd,worker   8m        v1.11.5
defg      Ready     controlplane,etcd,worker   8m        v1.11.5
hijk     Ready     controlplane,etcd,worker   8m        v1.11.5

```
Remove the cluster and perform rke up again with kubernetes version v1.12.5-rancher1-1.
```
$ kubectl get node --kubeconfig kube_config_cluster.yml
NAME             STATUS    ROLES                      AGE       VERSION
abcd   Ready     controlplane,etcd,worker   16m       v1.12.5
defg      Ready     controlplane,etcd,worker   16m       v1.12.5
hijk     Ready     controlplane,etcd,worker   16m       v1.12.5


```

**Closed by soumyalj** 2019-02-08 22:40 UTC
Labels: kind/bug, status/resolved, status/to-test
