### ISSUE TITLE
Centos 7 Segmentation fault

### ISSUE THREAD

**Issue by adalga** [rancher/rke#313] opened 2018-02-05 12:47 UTC
**RKE version:**
v0.1.1-rc1

**Docker version:**
17.03.2-ce

**Operating system and kernel:**
``` 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
Kernel version: `3.10.0-693.17.1.el7.x86_64`

**Type/provider of hosts:**
Vmware Workstation 12 Player

**cluster.yml file:**
```
---

kubernetes_version: v1.8.5-rancher4

auth:
  strategy: x509
  options:
    foo: bar

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS or GCE, use the network plugin config option:
# 'calico_cloud_provider: aws'
# or
# 'calico_cloud_provider: gce'
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

ssh_key_path: ~/.ssh/id_rsa
enforce_docker_version: false
# Kubernetes authorization mode; currently only `rbac` is supported and enabled by default.
# Use `mode: none` to disable authorization
authorization:
  mode: rbac
  options:


# List of registry credentials, if you are using a Docker Hub registry,
# you can omit the `url` or set it to `docker.io`
private_registries:
  - url: docker.io
    user: Username
    passowrd: password

nodes:
  - address: 192.168.112.144
    user: turkuaz
    role: [controlplane,worker,etcd]
    ssh_key_path: ~/.ssh/id_rsa
    
  - address: 192.168.112.145
    user: turkuaz
    role: [controlplane,worker,etcd]
    ssh_key_path: ~/.ssh/id_rsa
    
  - address: 192.168.112.146
    user: turkuaz
    role: [controlplane,worker,etcd]
    ssh_key_path: ~/.ssh/id_rsa

services:
  etcd:

  kube-api:

    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:



system_images:
  etcd: rancher/etcd:v3.0.17
  kubernetes: rancher/k8s:v1.8.5-rancher4
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  kubernetes_services_sidecar: rancher/rke-service-sidekick:v0.1.0
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0

# all addon manifests MUST specify a namespace
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-nginx
      namespace: default
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
```

**Steps to Reproduce:**
`sudo ./rke up`

**Results:**
`Segmentation fault`

When I try to rke up on Centos 7 I get segmentation fault. I tried same setup with ubuntu 16.04 and it works. However, Centos 7 gives segmentation fault.

**Comment by superseb** [comment] 2018-02-05 14:45
Copy-pasting the `cluster.yml` does not reproduce on CentOS7 with that kernel. Can you run `sudo ./rke --debug up`?

**Comment by akd31** [comment] 2018-02-05 14:59
Again it gives segmentation Segmentation fault

**Comment by akd31** [comment] 2018-02-06 06:26
I reinstalled Centos and it works.

**Comment by akd31** [comment] 2018-02-07 13:23
When I try v0.1.1-rc2 release  I got segmentation fault again and then I tried old version which worked before but it gave segmentation fault too.

**Comment by galal-hussein** [comment] 2018-02-08 19:15
@adalga can you provide full logs and where do you get `segmentation fault` exactly?

**Comment by adalga** [comment] 2018-02-09 05:30
There is no log. It immediately gives segmentation fault after execute ./rke up .

**Comment by adalga** [comment] 2018-02-09 06:06
![segmentation](https://user-images.githubusercontent.com/13197483/36013971-6e2a61dc-0d78-11e8-864a-bd1c959ff2c1.JPG)

I reinstalled new Centos 7.3 Gnome Desktop. I tried both rke_linux-amd64 and rke releases and they both gave segmentation fault as above.

**Comment by superseb** [comment] 2018-04-12 14:17
@adalga Can you try to reproduce outside of your machine/VMWare Workstation? I have not seen a single report around this which makes me believe the host is overloaded/has bad memory or some other configuration causing this.

**Comment by adalga** [comment] 2018-04-12 16:59
Actually I gave it up and started to work on Ubuntu.

**Comment by deniseschannon** [comment] 2018-05-09 04:14
@adalga Since you've moved on to Ubuntu and we haven't had any other reports, I'll close this issue out.

**Closed by deniseschannon** 2018-05-09 04:14 UTC

**Comment by Trojaner** [comment] 2020-04-28 02:55
I am having the same issue on Ubuntu 19.10 where it just displays "Segmentation fault"
